### PR TITLE
feat: add more delegate choices for TFLite backend

### LINKED ISSUE #708: Add more delegate choices to TFLite backend
We have implemented delegate choices at https://github.com/mlcommons/mobile_app_open/pull/674
Now we need to add more delegate choices for the TFLite backend.

### PR DESCRIPTION
**Pull request by anhappdev**
Closes #708

### CODE REVIEW

**Comment by anhappdev** [comment]
@freedomtan Please check if I chose the correct model for the GPU delegate.

**Comment by freedomtan** [comment]
> Using this config
> 
> ```
>   delegate_choice: {
>     delegate_name: "GPU"
>     accelerator_name: "gpu"
>     accelerator_desc: "GPU"
>     model_path: "https://github.com/mlcommons/mobile_models/raw/main/v0_7/tflite/mobilenet_edgetpu_224_1.0_float.tflite"
>     model_checksum: "0da3fa6adc8bbaaeb0b5647e2d46c8a4"
>     batch_size: 2
>   }
> ```
> 
> my Samsung phone crashed with this log
> 
> ```
> E/tflite  (20060): TfLiteGpuDelegate Invoke: GpuDelegate must run on the same thread where it was initialized.
> E/tflite  (20060): Node number 78 (TfLiteGpuDelegateV2) failed to invoke.
> E/native  (20060): cpp/backend_tflite/tflite_c.cc:477 Failed to run the inference
> F/native  (20060): flutter/cpp/backends/external.h:158 Error while inferencing model
> F/libc    (20060): Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 20216 (DartWorker), pid 20060 (oid.mlperfbench)
> ```
> 
> So I removed it for now.

that's because the [mobilenet_edgetpu_224_1.0_float.tflite](https://github.com/mlcommons/mobile_models/raw/main/v0_7/tflite/mobilenet_edgetpu_224_1.0_float.tflite) doesn't support dynamic batch size.

**Comment by freedomtan** [comment]
These models look fine. However, we need 
```
<uses-library android:name="libOpenCL.so"
           android:required="false"/>

<uses-library android:name="libOpenCL-pixel.so"
           android:required="false"/>
....
```
otherwise, on Android 12 or later, we got messages like 
```
05-30 14:54:57.407 12551 12581 I native  : cpp/flutter/dart_backend_match.cc:12 checking backend 'libtflitebackend.so' ...
05-30 14:54:57.408 12551 12581 I native  : cpp/backend_tflite/tflite_c.cc:199 TFLite backend matches hardware
05-30 14:55:18.045 12551 12629 I native  : cpp/flutter/dart_run_benchmark.cc:31 in->backend_model_path=/storage/emulated/0/Android/data/org.mlcommons.android.mlperfbench/files/loaded_resources/github.com/mlcommons/mobile_models/raw/main/v0_7/tflite/mobilenet_edgetpu_224_1.0_float.tflite
05-30 14:55:18.045 12551 12629 I native  : cpp/flutter/dart_run_benchmark.cc:32 in->backend_lib_path=libtflitebackend.so
05-30 14:55:18.046 12551 12629 I native  :   framework: "TFLite"
05-30 14:55:18.046 12551 12629 I native  :     model_path: "https://github.com/mlcommons/mobile_models/raw/main/v0_7/tflite/mobilenet_edgetpu_224_1.0_uint8.tflite"
05-30 14:55:18.046 12551 12629 I native  :     model_path: "https://github.com/mlcommons/mobile_models/raw/main/v0_7/tflite/mobilenet_edgetpu_224_1.0_float.tflite"
05-30 14:55:18.049 12551 12629 I tflite  : Created TensorFlow Lite delegate for GPU.
05-30 14:55:18.050 12551 12629 I tflite  : Initialized TensorFlow Lite runtime.
05-30 14:55:18.052 12551 12629 I tflite  : Replacing 77 node(s) with delegate (TfLiteGpuDelegateV2) node, yielding 1 partitions.
05-30 14:55:18.083 12551 12629 E tflite  : Can not open OpenCL library on this device - dlopen failed: library "libOpenCL.so" not found
05-30 14:55:18.083 12551 12629 E tflite  : Falling back to OpenGL
05-30 14:55:18.092 12551 12629 I tflite  : Initialized OpenGL-based API.
05-30 14:55:18.190 12551 12629 I tflite  : Created 1 GPU delegate kernels.
05-30 14:56:18.969 12551 12629 I native  : cpp/flutter/dart_run_benchmark.cc:147 out->backend_name=TFLite


```

**Comment by anhappdev** [comment]
> that's because the [mobilenet_edgetpu_224_1.0_float.tflite](https://github.com/mlcommons/mobile_models/raw/main/v0_7/tflite/mobilenet_edgetpu_224_1.0_float.tflite) doesn't support dynamic batch size. We can convert a dynamic batch size one from TF pb file.

I will convert the model and add a new delegate choice for it in another PR.

**Review by freedomtan — APPROVED** [review]

**Pull request merged**
