### PR TITLE
fix: resolve crash on Play Store version

### PR DESCRIPTION
**Pull request by anhappdev**
* Closes https://github.com/mlcommons/mobile_app_open/issues/893

### CODE REVIEW

**Comment by mohitmundhragithub** [comment]
@anhappdev do you want me to try out this version of the app from the playstore?

**Comment by anhappdev** [comment]
> @anhappdev do you want me to try out this version of the app from the playstore?

Yes. Please.

**Comment by mohitmundhragithub** [comment]
> > @anhappdev do you want me to try out this version of the app from the playstore?
> 
> Yes. Please.

i see the play store version was updated on 18th June. Can you push the apk with these fixes as well to playstore?

**Comment by anhappdev** [comment]
> i see the play store version was updated on 18th June. Can you push the apk with these fixes as well to playstore?

@mohitmundhragithub I am not sure why it shows that date. Can you check the app build number in the settings screen. The build number from this PR should be `156`?

**Comment by mohitmundhragithub** [comment]
the latest version that i downloaded is 156 only. 



but sadly, this also doesn't work.

**Comment by anhappdev** [comment]
@mohitmundhragithub Ok. Thanks for the feedback. Is the crash occurred on any Android devices with the QTI backend or only on the Galaxy S23?

**Comment by mohitmundhragithub** [comment]
I tried the apk on another device (Samsung galaxy tab s8+). It crashes there as well. 

Sadly I am still unable to upload the device logs... but following up with IT team internally.

**Comment by freedomtan** [comment]
@anhappdev please add koansin.tan@gmail.com for internal testing

**Comment by mohitmundhragithub** [comment]
[Galaxy S23 Ultra.txt](https://github.com/user-attachments/files/16023903/Galaxy.S23.Ultra.txt)

Hi Anh,

Finally able to upload the logs. Can you please check?

**Comment by anhappdev** [comment]
> [Galaxy S23 Ultra.txt](https://github.com/user-attachments/files/16023903/Galaxy.S23.Ultra.txt)
> 
> Hi Anh,
> 
> Finally able to upload the logs. Can you please check?

It looks like the same issue we have here:
https://github.com/mlcommons/mobile_app_open/pull/859#issuecomment-1969462799

For this issue, I still cannot find a solution.

**Comment by mohitmundhragithub** [comment]
actually the reason for failure is same. But the reason would be different. Seems like when uploading to playstore, the DSP access gets denied but not otherwise.

**Comment by freedomtan** [comment]
Let's see if we can
1. aab (in the CI) -> apk
2. try to get supported.
3. @freedomtan to try on MTK devices (or Samsung devices).

**Comment by freedomtan** [comment]
Works on

- MTK devices: both newer .dla  and older TFLite Neuron Delegate work
- Pixel 8 Pro: works

@AhmedTElthakeb and @Mostelk: please check if the Play Store apk works on Exynos devices.

**Comment by anhappdev** [comment]
I opened a support ticket on Google Play, but they don't provide support for this kind of issue. Here is their answer:

> Thanks for reaching out to Google Play Technical Support.
> Although I’m happy to answer any questions about managing your apps on the Google Play Console, our team isn’t trained to provide technical support for app development questions.

**Comment by freedomtan** [comment]
@AhmedTElthakeb will try to run the in Play Store one w/ SELinux disabled (if that works, we are almost sure that there is some kind of permission setting problem).

**Comment by anhappdev** [comment]
I don't know if it makes a different, but I deployed the app to the closed testing channel. 
Compared to the internal testing channel, a user still needs to be invited to join the testing program (so it's not public), but the app is reviewed by Google on every release, so I hope maybe the app will not be classified as "untrusted app" anymore.

@mohitmundhragithub @AhmedTElthakeb Can you please test the app (v4.1.0 (164)) again:
https://play.google.com/apps/testing/org.mlcommons.android.mlperfbench

**Comment by mohitmundhragithub** [comment]
> I don't know if it makes a different, but I deployed the app to the closed testing channel. Compared to the internal testing channel, a user still needs to be invited to join the testing program (so it's not public), but the app is reviewed by Google on every release, so I hope maybe the app will not be classified as "untrusted app" anymore.
> 
> @mohitmundhragithub @AhmedTElthakeb Can you please test the app (v4.1.0 (164)) again: https://play.google.com/apps/testing/org.mlcommons.android.mlperfbench

didn't work on GS23Ultra.

**Comment by freedomtan** [comment]
on rooted device, `adb shell` then `setenfoce 0`, and `adb shell setenforce 0` (meaning disabling all the permission checks by the SELinux). @mohitmundhragithub and @AhmedTElthakeb

**Comment by mohitmundhragithub** [comment]
I think I found one workaround for the issue. 

For QTI backend, if we push few of the dependent libs to the "files" folder, instead of packing it in the apk's "lib" folder, then the issue gets resolved for qti backend.
I want to try it out for the app to be downloaded from the play store. 

@anhappdev, i will push a change to this PR... can you please help to push the aab file to the playstore? i can test with that.

**Comment by anhappdev** [comment]
@mohitmundhragithub You can just push directly to this branch `anh/debug-play-store-version`. The CI will deploy the AAB to Play Store automatically.

**Comment by anhappdev** [comment]
@mohitmundhragithub You can just push directly to this branch `anh/debug-play-store-version`. The CI will deploy the AAB to Play Store automatically.

**Comment by anhappdev** [comment]
It will also reopen the PR.

**Review by mohitmundhragithub — DISMISSED** [review]

**Comment by mohitmundhragithub** [comment]
> @mohitmundhragithub You can just push directly to this branch `anh/debug-play-store-version`. The CI will deploy the AAB to Play Store automatically.

which task will push to playstore?

**Comment by mohitmundhragithub** [comment]
> @mohitmundhragithub You can just push directly to this branch `anh/debug-play-store-version`. The CI will deploy the AAB to Play Store automatically.

@anhappdev , the app got deployed to play store successfully, but the date in play store still shows 21st july. How long does it take to update?

**Comment by anhappdev** [comment]
> @anhappdev , the app got deployed to play store successfully, but the date in play store still shows 21st july. How long does it take to update?

I don't know that. And I don't know if that date get updated. But you can check the build number displayed in the app settings screen to make sure it's the expected version.

**Comment by mohitmundhragithub** [comment]
it says version: 4.1.0 | build: 164... which seems to be same as before :(

**Comment by mohitmundhragithub** [comment]
> > @anhappdev , the app got deployed to play store successfully, but the date in play store still shows 21st july. How long does it take to update?
> 
> I don't know that. And I don't know if that date get updated. But you can check the build number displayed in the app settings screen to make sure it's the expected version.

@anhappdev, can you please push it manually?

**Comment by mohitmundhragithub** [comment]
> > @anhappdev, can you please push it manually?
> 
> The app `4.1.0 (245)` is available on the internal track. Maybe you can try delete and reinstall the current version on your phone?

https://play.google.com/store/apps/details?id=org.mlcommons.android.mlperfbench&pcampaignid=web_share

Is this the correct link? Somehow for my account, its not showing the correct version. I tried unisntalling / installing again on multiple devices.

**Comment by mohitmundhragithub** [comment]
> > > @anhappdev, can you please push it manually?
> > 
> > 
> > The app `4.1.0 (245)` is available on the internal track. Maybe you can try delete and reinstall the current version on your phone?
> 
> https://play.google.com/store/apps/details?id=org.mlcommons.android.mlperfbench&pcampaignid=web_share
> 
> Is this the correct link? Somehow for my account, its not showing the correct version. I tried unisntalling / installing again on multiple devices.

may be it takes some time to reach my region (india). will wait for some more time.

**Comment by mohitmundhragithub** [comment]
> > > > @anhappdev, can you please push it manually?
> > > 
> > > 
> > > The app `4.1.0 (245)` is available on the internal track. Maybe you can try delete and reinstall the current version on your phone?
> > 
> > https://play.google.com/store/apps/details?id=org.mlcommons.android.mlperfbench&pcampaignid=web_share
> > 
> > Is this the correct link? Somehow for my account, its not showing the correct version. I tried unisntalling / installing again on multiple devices.
> 
> may be it takes some time to reach my region (india). will wait for some more time.

@anhappdev its not updated yet in playstore. Could this be acount related issue? Can you please check?

**Comment by anhappdev** [comment]
@mohitmundhragithub The link is in this comment:
https://github.com/mlcommons/mobile_app_open/issues/893#issue-2360966998

Please noted the “internaltest” in the url.

**Comment by freedomtan** [comment]
> @mohitmundhragithub The link is in this comment: [#893 (comment)](https://github.com/mlcommons/mobile_app_open/issues/893#issue-2360966998)
> 
> Please noted the “internaltest” in the url.

@mohitmundhragithub I am told the one from Play Store works on a Samsung S24+ (8 Gen 3 inside).

**Comment by mohitmundhragithub** [comment]
> > @mohitmundhragithub The link is in this comment: [#893 (comment)](https://github.com/mlcommons/mobile_app_open/issues/893#issue-2360966998)
> > Please noted the “internaltest” in the url.
> 
> @mohitmundhragithub I am told the one from Play Store works on a Samsung S24+ (8 Gen 3 inside).

That's surprising. Not sure how that could happen. The apk when sideloaded should work fine, but not the app from play store.

**Comment by mohitmundhragithub** [comment]
> @mohitmundhragithub The link is in this comment: [#893 (comment)](https://github.com/mlcommons/mobile_app_open/issues/893#issue-2360966998)
> 
> Please noted the “internaltest” in the url.

Thanks a lot @anhappdev. This link worked fine. I am able to download the updated app now.

The workaround that i had worked fine. Now we need to have a proper fix for the same.
My suggestion is,

1) Add a field in the backend settings, and list the required dependent library.
2) We need to host the required dependent library somewhere, which the app downloads and saves in "/sdcard/Android/data/org.mlcommons.android.mlperfbench/files".
3) The above path needs to be known to the backend. So, either we can have a fixed path or pass the dynamic download location path to the backend, so that the backend can use this path. For QTI backend, we set the env variable "ADSP_LIBRARY_PATH" to do this.

**Comment by mohitmundhragithub** [comment]
> > @mohitmundhragithub The link is in this comment: [#893 (comment)](https://github.com/mlcommons/mobile_app_open/issues/893#issue-2360966998)
> > Please noted the “internaltest” in the url.
> 
> Thanks a lot @anhappdev. This link worked fine. I am able to download the updated app now.
> 
> The workaround that i had worked fine. Now we need to have a proper fix for the same. My suggestion is,
> 
> 1. Add a field in the backend settings, and list the required dependent library.
> 2. We need to host the required dependent library somewhere, which the app downloads and saves in "/sdcard/Android/data/org.mlcommons.android.mlperfbench/files".
> 3. The above path needs to be known to the backend. So, either we can have a fixed path or pass the dynamic download location path to the backend, so that the backend can use this path. For QTI backend, we set the env variable "ADSP_LIBRARY_PATH" to do this.

NB: the other minSDK 30 issue also gets resolved with this workaround.

**Comment by mohitmundhragithub** [comment]
@anhappdev, @freedomtan  I have pushed the changes to download the libs directory as listed in the backend setting. Can you please review once?

**Comment by anhappdev** [comment]
> The workaround that i had worked fine. Now we need to have a proper fix for the same. Basically, with Android SDK 29 and onwards, the app can't use few libs from the /data/.../mlperf/libs folder. Workaround is to have the lib file present in the /sdcard/Android/data/...mlperfbench/files folder.
> 
> My suggestion is,
> 
> 1. Add a field in the backend settings, and list the required dependent library.
> 2. We need to host the required dependent library somewhere, which the app downloads and saves in "/sdcard/Android/data/org.mlcommons.android.mlperfbench/files".
> 3. The above path needs to be known to the backend. So, either we can have a fixed path or pass the dynamic download location path to the backend, so that the backend can use this path. For QTI backend, we set the env variable "ADSP_LIBRARY_PATH" to do this.

Another solution is to download the libs in the build step and put them in the same place where the native libs are:

https://github.com/mlcommons/mobile_app_open/blob/fad36c149fb710aadd4c5df9f55f3166090d9c46/flutter/android/android.mk#L50-L65

More info at https://developer.android.com/ndk/guides/abis#am

**Comment by freedomtan** [comment]
The cause of this issue is that the App cannot  access some of the .so libraries in devices (e.g., in either /system or /vendor partition). 

Why this restriction: there is some kind of SELinux rule(s) what preventing libraries not listed in a white list to be accessed by an App from the Play Store.

@mohitmundhragithub's solution is to copy the libraries the app needs to the App's library directory. However, I think this is a hack.

Long term solution: fix the "whitelist".

debugging hint: ld debug options (Android specific) to get more verbose ld outputs (which may help find the libraries been accessed), @freedomtan to find the options from Android documentation site

**Comment by mohitmundhragithub** [comment]
> > The workaround that i had worked fine. Now we need to have a proper fix for the same. Basically, with Android SDK 29 and onwards, the app can't use few libs from the /data/.../mlperf/libs folder. Workaround is to have the lib file present in the /sdcard/Android/data/...mlperfbench/files folder.
> > 
> > My suggestion is,
> > 
> > 1. Add a field in the backend settings, and list the required dependent library.
> > 2. We need to host the required dependent library somewhere, which the app downloads and saves in "/sdcard/Android/data/org.mlcommons.android.mlperfbench/files".
> > 3. The above path needs to be known to the backend. So, either we can have a fixed path or pass the dynamic download location path to the backend, so that the backend can use this path. For QTI backend, we set the env variable "ADSP_LIBRARY_PATH" to do this.
> 
> Another solution is to download the libs in the build step and put them in the same place where the native libs are:
> 
> https://github.com/mlcommons/mobile_app_open/blob/fad36c149fb710aadd4c5df9f55f3166090d9c46/flutter/android/android.mk#L50-L65
> 
> More info at https://developer.android.com/ndk/guides/abis#am

we have already been doing this. all the .so files are already part of the libs/abi folder. It used to work till now. however from, sdk 29 and above, there is an additional W^X restrictions.

there are a few libs required to access npu (suffixed skel.so), which have become inaccessible, from android 29 onwards.

i think there is similar restrictions for samsung stack as well.

when we copy the libs to files folder, the app is able to access those. this change facilitates that.

if we can find a way to pack these libs during build time to the files folder, then we dont need to download them separately.

**Comment by freedomtan** [comment]
Debug library loading issues: see https://android.googlesource.com/platform/bionic/+/master/android-changes-for-ndk-developers.md#enable-logging-of-dlopen_dlsym-and-library-loading-errors-for-apps-available-for-api-level-26

**Comment by anhappdev** [comment]
> we have already been doing this. all the .so files are already part of the libs/abi folder. It used to work till now. however from, sdk 29 and above, there is an additional W^X restrictions.
> 
> there are a few libs required to access npu (suffixed skel.so), which have become inaccessible, from android 29 onwards.

Really? Did you try copy the `*skel.so` file to `${flutter_android_libs_folder}` and test the app. All *.so files in `${flutter_android_libs_folder}` should be executable else the native backends would not work.

**Comment by anhappdev** [comment]
Did we try to specify all the libs in the [AndroidManifest.xml](https://github.com/mlcommons/mobile_app_open/blob/master/flutter/android/app/src/main/AndroidManifest.xml) with either [uses-native-library](https://developer.android.com/guide/topics/manifest/uses-native-library-element) or [uses-library](https://developer.android.com/guide/topics/manifest/uses-library-element) tag?
I don't know if it works, but maybe it's worth a try.

**Comment by anhappdev** [comment]
https://github.com/mlcommons/mobile_app_open/pull/929

**Comment by mohitmundhragithub** [comment]
> Did we try to specify all the libs in the [AndroidManifest.xml](https://github.com/mlcommons/mobile_app_open/blob/master/flutter/android/app/src/main/AndroidManifest.xml) with either [uses-native-library](https://developer.android.com/guide/topics/manifest/uses-native-library-element) or [uses-library](https://developer.android.com/guide/topics/manifest/uses-library-element) tag?
> I don't know if it works, but maybe it's worth a try.

yes. already tried this earlier.

**Comment by mohitmundhragithub** [comment]
> * https://github.com/mlcommons/mobile_app_open/pull/929

tried it. didnt work.

**Comment by mohitmundhragithub** [comment]
there is a IPC involved when trying to invoke the skel files. may be thats resulting in this behaviour.

same issue is seen for both playstore version and for apps with minsdkversion >= 29

**Comment by anhappdev** [comment]
Ok. Let move on with @mohitmundhragithub's solution: let the app download the *.so files.
But I will do it a bit different. I will push some new commits later.

**Comment by anhappdev** [comment]
@mohitmundhragithub Did we try to set [`android:extractNativeLibs="true"`](https://developer.android.com/guide/topics/manifest/application-element#extractNativeLibs) in the AndroidManifest.xml?

**Comment by mohitmundhragithub** [comment]
> @mohitmundhragithub Did we try to set [`android:extractNativeLibs="true"`](https://developer.android.com/guide/topics/manifest/application-element#extractNativeLibs) in the AndroidManifest.xml?
> 
> 1. Set `android:extractNativeLibs="true"` as in https://stackoverflow.com/a/64792194
> 2. Set `android.bundle.enableUncompressedNativeLibs=false` as in https://stackoverflow.com/a/56551499

the apk uploaded to play store (252) using PR #893 seems to resolve the play store issue at least on Galaxy S23 ultra.
Would be worthwhile to check if this can resolve the minSDKVersion 29 issue as well or not.

**Comment by anhappdev** [comment]
> Would be worthwhile to check if this can resolve the minSDKVersion 29 issue as well or not.

Yes. It also resolved the issue with QTI backend in the PR https://github.com/mlcommons/mobile_app_open/pull/859.

**Comment by anhappdev** [comment]
- Closed in favor of https://github.com/mlcommons/mobile_app_open/pull/930

**Pull request closed without merging**
