### PR TITLE
ui: new history screen

### PR DESCRIPTION
**Pull request by anhappdev**
* Part of #806
* New design for history screen

The original design has some problems:
- It probably based on an outdated version of the app, where we show a simple list of past run (each run contains multiple benchmarks)
- Since we want to sort and filter the results, we must show it at one deeper level (benchmark instead of run).
- For now, I just updated the old result screen with this new simple design. We can improve it further if our designer has some new design.

 → 

history

### CODE REVIEW

**Comment by anhappdev** [comment]
@banjo247 Please check my first comment related to the design.

**Review by freedomtan — APPROVED** [review]

**Comment by freedomtan** [comment]
@banjo247 ping, we need your comments

**Comment by freedomtan** [comment]
@anhappdev Let's remove the sorting feature, just sort the dates (either ascending or descending)

**Comment by anhappdev** [comment]
- New history screen https://github.com/mlcommons/mobile_app_open/pull/866

**Pull request merged**
