### PR TITLE
feat: use Cloudflare instead of GitHub for hosting models and datasets

### PR DESCRIPTION
**Pull request by anhappdev**

### CODE REVIEW

**Comment by freedomtan** [comment]
Should we merge this? Or test a bit first?

**Comment by anhappdev** [comment]
Please test it first.

**Comment by freedomtan** [comment]
@freedomtan to test it from Taiwan, VPN to some US sites.
@mohitmundhragithub to test it from India
@AhmedTElthakeb please help test it too.

**Comment by freedomtan** [comment]
With [android-apk-unified-262](https://github.com/mlcommons/mobile_app_open/actions/runs/12062906074/artifacts/2248093718), it seems to work fine.

**Review by freedomtan — APPROVED** [review]

**Comment by AhmedTElthakeb** [comment]
Seems to work fine. 
Is the custom dataset directory feature still supported here?

**Comment by anhappdev** [comment]
> Seems to work fine. Is the custom dataset directory feature still supported here?

We removed the "Access all files permission" so a custom dataset directory may not work.

**Pull request merged**
