### PR TITLE
feat: add About screen

### PR DESCRIPTION
**Pull request by anhappdev**
Part of #717 

APK for testing:
[2023-06-02_mlperfbench-a4b10ee-qsmgt.apk](https://drive.google.com/file/d/1gbPqxHAIlT_DmzhGKd0dF2NDvWwZQsmm/view?usp=sharing)

sha256: `195a110ab318f153631eb904abcffdda8c291c4e1ad9413ac68a5d447a1d0a1f`

### CODE REVIEW

**Review by freedomtan — APPROVED** [review]
LGTM. We need confirmations from other folks.

**Comment by freedomtan** [comment]
@mohitmundhragithub, @AhmedTElthakeb, and @Mostelk please confirm is this apk is OK

**Comment by AhmedTElthakeb** [comment]
@anhappdev 
Currently it says in the detailed results description
`samsung | samsung npu `

We would like to update it to
`samsung | exynos npu `

**Comment by freedomtan** [comment]
@mohitmundhragithub please report the status on Q devices
@freedomtan to try on Pixel 7

**Comment by mohitmundhragithub** [comment]
> @mohitmundhragithub please report the status on Q devices @freedomtan to try on Pixel 7

it works fine for QC.

**Comment by AhmedTElthakeb** [comment]
> @mohitmundhragithub, @AhmedTElthakeb, and @Mostelk please check if this apk is OK

Works fine for Samsung

**Pull request merged**
