### PR TITLE
Merge submission v2.0 into master

### PR DESCRIPTION
**Pull request by anhappdev**
Part of #278

### CODE REVIEW

**Comment by anhappdev** [comment]
Here is the app built with this branch:
[2022-04-16_PR292_mlperfbench_v2.0-qsmgt.apk](https://drive.google.com/file/d/1jv1nhdZ2pKQucZZgAbx1jDePXNuRU2rJ/view?usp=sharing)

**Comment by anhappdev** [comment]
Currently blocked by this issue:
https://github.com/mlcommons/mobile_app_open/issues/278#issuecomment-1097883953

**Comment by anhappdev** [comment]
@freedomtan @Mostelk @mohitmundhragithub @ptt2panda

Please test this build on your specific device to make sure that everything still works as expected.

[2022-04-28_PR292_mlperfbench_v2.0-qsmgt.apk](https://drive.google.com/file/d/1xzi1sc791YpF5tLoFGdQJzvi1j23Aq7B/view?usp=sharing)
This one is a Flutter app.

**Comment by anhappdev** [comment]
@d-uzlov Can you please check why the test `Build and test iOS Flutter app` is failed? I don't have access to Jenkins.

**Comment by d-uzlov** [comment]
@anhappdev there is some very massive syntactic error mostly complaining about `unknown type name 'NSString'` but also things like `@class`. My first impression is that it's trying to compile Objective C code as a C code. The error happened in bazel.

Here is the fill error:
<details>

```cpp
In file included from mobile_back_tflite/cpp/backend_tflite/tflite_c.cc:62:
In file included from external/org_tensorflow/tensorflow/lite/delegates/gpu/metal_delegate.h:19:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk/System/Library/Frameworks/Metal.framework/Headers/Metal.h:9:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk/System/Library/Frameworks/Metal.framework/Headers/MTLTypes.h:8:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:8:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:492:1: error: expected unqualified-id
@class NSString, Protocol;
^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:494:9: error: unknown type name 'NSString'
typedef NSString * NSExceptionName NS_EXTENSIBLE_STRING_ENUM;
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:495:9: error: unknown type name 'NSString'
typedef NSString * NSRunLoopMode NS_EXTENSIBLE_STRING_ENUM;
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:497:19: error: unknown type name 'NSString'
FOUNDATION_EXPORT NSString *NSStringFromSelector(SEL aSelector);
                  ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:498:44: error: unknown type name 'NSString'
FOUNDATION_EXPORT SEL NSSelectorFromString(NSString *aSelectorName);
                                           ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:500:19: error: unknown type name 'NSString'
FOUNDATION_EXPORT NSString *NSStringFromClass(Class aClass);
                  ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:501:53: error: unknown type name 'NSString'
FOUNDATION_EXPORT Class _Nullable NSClassFromString(NSString *aClassName);
                                                    ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:503:19: error: unknown type name 'NSString'
FOUNDATION_EXPORT NSString *NSStringFromProtocol(Protocol *proto) API_AVAILABLE(macos(10.5), ios(2.0), watchos(2.0), tvos(9.0));
                  ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:503:50: error: unknown type name 'Protocol'
FOUNDATION_EXPORT NSString *NSStringFromProtocol(Protocol *proto) API_AVAILABLE(macos(10.5), ios(2.0), watchos(2.0), tvos(9.0));
                                                 ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:504:19: error: unknown type name 'Protocol'
FOUNDATION_EXPORT Protocol * _Nullable NSProtocolFromString(NSString *namestr) API_AVAILABLE(macos(10.5), ios(2.0), watchos(2.0), tvos(9.0));
                  ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:504:61: error: unknown type name 'NSString'
FOUNDATION_EXPORT Protocol * _Nullable NSProtocolFromString(NSString *namestr) API_AVAILABLE(macos(10.5), ios(2.0), watchos(2.0), tvos(9.0));
                                                            ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:508:30: error: unknown type name 'NSString'
FOUNDATION_EXPORT void NSLog(NSString *format, ...) NS_FORMAT_FUNCTION(1,2) NS_NO_TAIL_CALL;
                             ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:508:53: error: format argument not an NSString
FOUNDATION_EXPORT void NSLog(NSString *format, ...) NS_FORMAT_FUNCTION(1,2) NS_NO_TAIL_CALL;
                             ~~~~~~~~~~~~~~~~       ^                  ~
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:94:49: note: expanded from macro 'NS_FORMAT_FUNCTION'
        #define NS_FORMAT_FUNCTION(F,A) __attribute__((format(__NSString__, F, A)))
                                                       ^                    ~
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:509:31: error: unknown type name 'NSString'
FOUNDATION_EXPORT void NSLogv(NSString *format, va_list args) NS_FORMAT_FUNCTION(1,0) NS_NO_TAIL_CALL;
                              ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:509:63: error: format argument not an NSString
FOUNDATION_EXPORT void NSLogv(NSString *format, va_list args) NS_FORMAT_FUNCTION(1,0) NS_NO_TAIL_CALL;
                              ~~~~~~~~~~~~~~~~                ^                  ~
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:94:49: note: expanded from macro 'NS_FORMAT_FUNCTION'
        #define NS_FORMAT_FUNCTION(F,A) __attribute__((format(__NSString__, F, A)))
                                                       ^                    ~
In file included from mobile_back_tflite/cpp/backend_tflite/tflite_c.cc:62:
In file included from external/org_tensorflow/tensorflow/lite/delegates/gpu/metal_delegate.h:19:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk/System/Library/Frameworks/Metal.framework/Headers/Metal.h:9:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk/System/Library/Frameworks/Metal.framework/Headers/MTLTypes.h:8:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:10:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSArray.h:5:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObject.h:8:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSZone.h:9:1: error: expected unqualified-id
@class NSString;
^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSZone.h:19:63: error: unknown type name 'NSString'
FOUNDATION_EXPORT void NSSetZoneName(NSZone * _Nullable zone, NSString *name)NS_SWIFT_UNAVAILABLE("Zone-based memory management is unavailable");
                                                              ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSZone.h:20:19: error: unknown type name 'NSString'
FOUNDATION_EXPORT NSString *NSZoneName(NSZone * _Nullable zone) NS_SWIFT_UNAVAILABLE("Zone-based memory management is unavailable");
                  ^
In file included from mobile_back_tflite/cpp/backend_tflite/tflite_c.cc:62:
In file included from external/org_tensorflow/tensorflow/lite/delegates/gpu/metal_delegate.h:19:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk/System/Library/Frameworks/Metal.framework/Headers/Metal.h:9:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk/System/Library/Frameworks/Metal.framework/Headers/MTLTypes.h:8:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:10:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSArray.h:5:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObject.h:10:1: error: expected unqualified-id
@class NSInvocation, NSMethodSignature, NSCoder, NSString, NSEnumerator;
^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
```

</details>

When I tried building the branch locally on my macbook I got the same error.

I was able to fix it by reverting tensorflow version in the `WORKSPACE` file back to 2.6.0.
Maybe 2.8.0 is broken for iOS, or maybe there were some breaking changes that are not accounted for in the submission 2.0 branch.

**Comment by d-uzlov** [comment]
Oh, I remembered that freedomtan also said about some issues with iOS when building with TF 2.8.0, and PR https://github.com/mlcommons/mobile_app_open/pull/268 contains some iOS-specific fixes.

I think we should revert TF version change from this PR and update it later in that separate PR. We even have a separate issue to update it.

**Comment by freedomtan** [comment]
> Oh, I remembered that @freedomtan also talked about some issues with iOS when building with TF 2.8.0, and his PR #268 contains some iOS-specific fixes.
> 

as far as I can remember, it's because of a change in metal delegate. It's something like including "<Metal/Metal.h>", which is includes some Objective-C headers, in C++ (.cc) code. By default, clang doesn't allow objective-c code in .cc   source code.

**Comment by freedomtan** [comment]
> @freedomtan @Mostelk @mohitmundhragithub @ptt2panda
> 
> Please test this build on your specific device to make sure that everything still works as expected.
> 
> App built WITH_TFLITE=1 WITH_MEDIATEK=1 WITH_PIXEL=1 run without issue on my test Android phone (TFLite backend) [2022-04-28_PR292_mlperfbench_v2.0-t.apk](https://drive.google.com/file/d/1sH2oTJDRuH-ZFWO2dBYcNIlCZB34s7ES/view?usp=sharing) [2022-04-28_PR292_mlperfbench_v2.0-mgt.apk](https://drive.google.com/file/d/17SFHgvtrzRPRHP-ku5Zntb5qw_UOxyqE/view?usp=sharing)
> 
> App built either WITH_SAMSUNG=1 or WITH_QTI=1 or both caused a crash on my phone. [2022-04-28_PR292_mlperfbench_v2.0-qsmgt.apk](https://drive.google.com/file/d/1xzi1sc791YpF5tLoFGdQJzvi1j23Aq7B/view?usp=sharing)
> 
> All apps in this PR is Flutter app.

The qsmgt.apk one could finish running on Xiaomi Redmi K50 Pro (a Dimensity 9000 phone). However,

1. there are only five benchmarks (I expected the `Mosaic`, the new segmentation model, to be added)
2. performance numbers are wrong. It seems settings and neuron delegate were not updated. I'll check the details later.

**Comment by freedomtan** [comment]
@AhmedTElthakeb tried and the app crashed. Please work with @anhappdev to resolve this.

**Comment by freedomtan** [comment]
generally, we don't have the new Mosaic because tasks file was not updated. (https://github.com/mlcommons/mobile_models/pull/40) is supposed to resolve this.

backend | status | tested by
-- | -- | --
Google |  |  |
MediaTek | it runs, but there is huge performance gap | @freedomtan
Qualcomm |   |  
Samsung |  crashed |  
Intel | under active development | @shabanim

**Comment by anhappdev** [comment]
Here are the new APKs (built from commit `5b65d1c423cb1340939a5b3a5c3c5879630660fa`):
[PR292 APKs](https://drive.google.com/drive/folders/16u5GnnwTOcPtZFMpbJgY8U6-AbpJjdUx?usp=sharing)

Some changes of the APKs `2022-05-04` vs. `2022-04-28` are:
1. Use the new task file with IS Mosaic.
2. Use TF2.6

**Comment by kcwu** [comment]
I tested on a Google Pixel 6 and the build works as expected.

**Comment by mohitmundhragithub** [comment]
> Here are the new APKs (built from commit `5b65d1c423cb1340939a5b3a5c3c5879630660fa`): [PR292 APKs](https://drive.google.com/drive/folders/16u5GnnwTOcPtZFMpbJgY8U6-AbpJjdUx?usp=sharing) I built a separated APK for each backend to make testing easier.
> 
> Some changes of the APKs `2022-05-04` vs. `2022-04-28` are:
> 
> 1. Use the new task file with IS Mosaic.
> 2. Use TF2.6

I tried the qualcomm apk shared here. It seems to work fine. Couple of questions related to the app -- 
1) the cooldown time is 0 by default in this apk. In our older app it was 5 minutes. Is it ok?
2) There is one option of offline mode in the settings. Can you please explain the use of it and how to use it?

**Comment by anhappdev** [comment]
Status update: @AhmedTElthakeb helped to resolve the crash with Samsung supported device. But the unified app still crashes on Samsung non-supported device. It looks like the unified app crashes when it cannot detect Samsung backend instead of falling through and check for other backends.

**Comment by freedomtan** [comment]
> Status update: @AhmedTElthakeb helped to resolve the crash with Samsung supported device. But the unified app still crashes on Samsung non-supported device. It looks like the unified app crashes when it cannot detect Samsung backend instead of falling through and check for other backends.

is this related to old issue (https://github.com/mlcommons/mobile_app_open/issues/231) we had before? or this is a new one?

**Comment by freedomtan** [comment]
@AhmedTElthakeb and @freedomtan to test on other devices.  

what @anhappdev reported: Samsung backend + TFLite on non-supported Samsung devices (say S20 or S21 (?))

**Comment by anhappdev** [comment]
Samsung and QTI backend use the same `libc++_shared.so` file but from different sources so I got this error when building the unified app:

```
rm -rf flutter/android/app/src/main/jniLibs/arm64-v8a
mkdir -p flutter/android/app/src/main/jniLibs/arm64-v8a
cp -f \
        bazel-bin/mobile_back_tflite/cpp/backend_tflite/libtflitebackend.so \
         \
         \
        bazel-bin/mobile_back_qti/cpp/backend_qti/libqtibackend.so mobile_back_qti/snpe-1.59.1.3230/lib/aarch64-android-clang8.0/libc++_shared.so mobile_back_qti/snpe-1.59.1.3230/lib/aarch64-android-clang8.0/libSNPE.so mobile_back_qti/snpe-1.59.1.3230/lib/aarch64-android-clang8.0/libhta.so mobile_back_qti/snpe-1.59.1.3230/lib/aarch64-android-clang8.0/libsnpe_dsp_domains_v2.so mobile_back_qti/snpe-1.59.1.3230/lib/aarch64-android-clang8.0/libsnpe_dsp_domains_v3.so mobile_back_qti/snpe-1.59.1.3230/lib/aarch64-android-clang8.0/libSnpeHtpV69Stub.so mobile_back_qti/snpe-1.59.1.3230/lib/aarch64-android-clang8.0/libSnpeHtpV68Stub.so mobile_back_qti/snpe-1.59.1.3230/lib/aarch64-android-clang8.0/libSnpeHtpPrepare.so mobile_back_qti/snpe-1.59.1.3230/lib/dsp/libsnpe_dsp_v66_domains_v2_skel.so mobile_back_qti/snpe-1.59.1.3230/lib/dsp/libsnpe_dsp_v68_domains_v3_skel.so mobile_back_qti/snpe-1.59.1.3230/lib/dsp/libSnpeHtpV69Skel.so mobile_back_qti/snpe-1.59.1.3230/lib/dsp/libSnpeHtpV68Skel.so \
        bazel-bin/flutter/android/commonlibs/lib_arm64/libc++_shared.so mobile_back_samsung/samsung/lib/libsamsungbackend.so mobile_back_samsung/samsung/lib/libenn_public_api_cpp.so mobile_back_samsung/samsung/lib/libsbe2200_core.so mobile_back_samsung/samsung/lib/libsbe1200_core.so mobile_back_samsung/samsung/lib/libc++.so mobile_back_samsung/samsung/lib/libeden_nn_on_system.so  \
        bazel-bin/flutter/cpp/flutter/libbackendbridge.so \
        flutter/android/app/src/main/jniLibs/arm64-v8a
cp: will not overwrite just-created 'flutter/android/app/src/main/jniLibs/arm64-v8a/libc++_shared.so' with 'bazel-bin/flutter/android/commonlibs/lib_arm64/libc++_shared.so'
make: *** [flutter/android.mk:85: flutter/android/libs] Error 1
make: *** [flutter/android.mk:66: docker/flutter/android/apk] Error 2
```

@mohitmundhragithub 
I updated the `qti_backend.mk` to use the `${BAZEL_LINKS_PREFIX}bin/flutter/android/commonlibs/lib_arm64/libc++_shared.so`, see commit [1d73a3a](https://github.com/mlcommons/mobile_app_open/pull/292/commits/1d73a3a2e1e8ba9b9037db39db7041a1f82981e2). Please check if that is ok.

**Comment by anhappdev** [comment]
I uploaded the new APKs `2022-05-10_*.apk` built with commit `1d73a3a` in this folder [PR292](https://drive.google.com/drive/folders/16u5GnnwTOcPtZFMpbJgY8U6-AbpJjdUx).
The change of the APKs `2022-05-10` vs. `2022-05-04` is that the updated Samsung backend code is used.

**Comment by freedomtan** [comment]
FYR, on a *Samsung S21 5G SM-G991B* I borrowed from a colleague, it crashed. That is, I confirmed what @anhappdev reported. Please check if this is expected behavior.

**Comment by freedomtan** [comment]
@Mostelk will help check if the S21 unsupported message is expected behavior or not.

**Comment by freedomtan** [comment]
@anhappdev please re-base and merge this

**Review by d-uzlov — CHANGES_REQUESTED** [review]
Is it possible to exclude binary libraries from sources? Maybe they can be automatically downloaded from somewhere?
* mobile_back_tflite/cpp/backend_tflite/libneuronusdk_adapter.mtk.so.5
* mobile_back_tflite/cpp/backend_tflite/neuron/tensorflow-lite-neuron.aar

We even have a CI check that will fail if known binary files are included into git. Unfortunately, `.5` and `.aar` file extensions are not checked on CI but I would still prefer not to have binary libraries in the master branch.

**Comment by anhappdev** [comment]
> Is it possible to exclude binary libraries from sources? Maybe they can be automatically downloaded from somewhere?
> 
> * mobile_back_tflite/cpp/backend_tflite/libneuronusdk_adapter.mtk.so.5
> * mobile_back_tflite/cpp/backend_tflite/neuron/tensorflow-lite-neuron.aar

@freedomtan Those files are for MediaTek backend, right?

**Comment by freedomtan** [comment]
> > Is it possible to exclude binary libraries from sources? Maybe they can be automatically downloaded from somewhere?
> > 
> > * mobile_back_tflite/cpp/backend_tflite/libneuronusdk_adapter.mtk.so.5
> > * mobile_back_tflite/cpp/backend_tflite/neuron/tensorflow-lite-neuron.aar
> 
> @freedomtan Those files are for MediaTek backend, right?

Yes, I'll ask MTK colleagues to update the source code of [Neuron Delegate](https://github.com/MediaTek-NeuroPilot/tflite-neuron-delegate) then we can use Neuron Delegate source code instead of binary aar. There were some internal changes not pushed to the Neuron Delegate repo yet.

The `libneuronusdk_adapter.mtk.so.5` should be not be needed. Shipping devices should have newer binary now.

**Comment by freedomtan** [comment]
> @freedomtan is there an estimate of much it will take? If it's more than, say, two weeks, then we can probably delete `.so.5` file and merge this with `.aar` file, and create an issue to refactor it when neuron delegate sources are available.

It shouldn't take that long, however, our Neuron Delegate guys are busy working on some internal projects recently. So, yup, it could be more than 2 weeks.

**Review by d-uzlov — APPROVED** [review]

**Comment by d-uzlov** [comment]
@anhappdev, could you please create an issue to remove the `.so` file after you merge it?

**Pull request merged**
