### PR TITLE
Samsung backend update 

### PR DESCRIPTION
**Pull request by AhmedTElthakeb**
Extending Samsung backend for Flutter app to more phones.

### CODE REVIEW

**Comment by d-uzlov** [comment]
@AhmedTElthakeb, you can add `<!-- markdown-link-check-disable-next-line -->` into mobile_back_samsung/README.md to fix CI.
Markdown check failed because mobile_back_samsung repo is private. CI doesn't use any special authorization so we have to exclude links to private resources from the check.

**Comment by d-uzlov** [comment]
@AhmedTElthakeb, I got protobuf parsing error when loading the Samsung backend: `Error parsing text-format mlperf.mobile.BackendSetting: 87:6: Message type "mlperf.mobile.BenchmarkSetting" has no field named "src"`
This is what backend config entry looks like:
```prototxt
benchmark_setting {
  benchmark_id: "IC_tpu_uint8"
...
  src: "https://github.com/mlcommons/mobile_models/raw/main/v1_0/Samsung/ic.nnc"
  md5_checksum: "955ef2ac3c134820eab901f3dac9f732"
  single_stream_expected_latency_ns: 900000
}
```
I also noticed that in the `samsung_backend_flutter_libs` branch in Samsung repo there are outdated source files.

We recently updated task ids (`IC_tpu_uint8` is no longer valid) and backend task config format:
* https://github.com/mlcommons/mobile_app_open/pull/500

It seems that you used an old commit to build the libs.
Could you please check this?

**Comment by AhmedTElthakeb** [comment]
> @AhmedTElthakeb, I got protobuf parsing error when loading the Samsung backend: `Error parsing text-format mlperf.mobile.BackendSetting: 87:6: Message type "mlperf.mobile.BenchmarkSetting" has no field named "src"` This is what backend config entry looks like:
> 
> ```
> benchmark_setting {
>   benchmark_id: "IC_tpu_uint8"
> ...
>   src: "https://github.com/mlcommons/mobile_models/raw/main/v1_0/Samsung/ic.nnc"
>   md5_checksum: "955ef2ac3c134820eab901f3dac9f732"
>   single_stream_expected_latency_ns: 900000
> }
> ```
> 
> I also noticed that in the `samsung_backend_flutter_libs` branch in Samsung repo there are outdated source files.
> 
> We recently updated task ids (`IC_tpu_uint8` is no longer valid) and backend task config format:
> 
> * [Update configs of Samsung backend #500](https://github.com/mlcommons/mobile_app_open/pull/500)
> 
> It seems that you used an old commit to build the libs. Could you please check this?

@d-uzlov I reviewed the latest modifications and updated accordingly, could you please try now and let me know if you face any issues?

**Comment by d-uzlov** [comment]
@AhmedTElthakeb, backend failed on my phone due to missing lib: `libofi_rt_framework_user_vendor.so`
```log
[Backend][sbe] load_core_library:80: fail to get handle of shared library
[Backend][sbe] load_core_library:82: dlopen error with dlopen failed: library "libofi_rt_framework_user_vendor.so" not found: needed by /data/app/~~lvBbF2MXrFSf_P4bJR-bQA==/org.mlcommons.android.mlperfbench-WQ2c6_xFrHvVUDuS13GTwg==/lib/arm64/libsbe2100_core.so in namespace classloader-namespace
```
You can add it into the list of required libraries here to fix it:
https://github.com/mlcommons/mobile_app_open/blob/8c86121160afa131490c79244db9341d58f60ac1/mobile_back_samsung/samsung_backend.mk#L22-L25

I copied this file into android libs folder manually for testing, and then I got an error about `libeden_rt_stub.edensdk.samsung.so` missing:
```log
[Backend][sbe] load_core_library:82: dlopen error with dlopen failed: library "libeden_rt_stub.edensdk.samsung.so" not found: needed by /data/app/~~5Iq7lQTxwktI7a2YnQxflg==/org.mlcommons.android.mlperfbench-hMdKfGnhEpOmFIIZ3AKAaA==/lib/arm64/libeden_nn_on_system.so in namespace classloader-namespace
```

I don't see this lib in the mobile_back_samsung repo so I wasn't able fix it for testing.

Tested on S21+ SM G996B.

**Comment by AhmedTElthakeb** [comment]
@d-uzlov 
I updated the native libs.

**Review by d-uzlov — APPROVED** [review]
Looks good to me.
Works fine on S21+.

**Comment by AhmedTElthakeb** [comment]
@d-uzlov thanks for verifying.
Could you please share your apk with me so that I can also verify it on my side?

**Comment by d-uzlov** [comment]
Here's my APK:
https://drive.google.com/file/d/1YV1Nnq3IUUCs5OL8mAARikJY5hMbpCus/view?usp=sharing

**Comment by d-uzlov** [comment]
@AhmedTElthakeb do you need `samsung-backend` branch for anything? Can we delete it?

**Pull request merged**
