### PR TITLE
Android NDK r25 support

### PR DESCRIPTION
**Pull request by freedomtan**
1. NDK 25 and later is supported by tf master after https://github.com/tensorflow/tensorflow/commit/0caae80adf169e0106946b2d92faad362854f220
2. replacing TF-2.8 with TF master doesn't work. It seems there are some Python issues
3. I backported related changes from master to TF r2.14 branch and made diff (`//patches:ndk_25_r14.diff` in the diff)
4. C++14 --> C++17 because TF 2.14 requires C++17
5. remove our own code of `protobuffer`, `cpuinfo`, and Apple related bazel rules, because TF 2.14 should have newer dependencies
6. for NDK >= 25, `ANDROID_NDK_HOME`, ` ANDROID_NDK_VERSION` , and `ANDROID_NDK_API_LEVEL` are required.
  -- NDK >= 25: e.g., ANDROID_NDK_HOME=..., ANDROID_NDK_VERSION=25, ANDROID_NDK_API_LEVEL=33
  -- NDK <= 21: e.g., ANDROID_NDK_HOME=..., ANDROID_NDK_VERSION=21

I was able to build TFLite backend w/o and w/ MediaTek neuron delegate.

### CODE REVIEW

**Comment by anhappdev** [comment]
> ios: why do we need ANDROID SDK and NDK fro iOS as in https://github.com/mlcommons/mobile_app_open/blob/master/flutter/ios/ci_scripts/ci_post_clone.sh#L76-L90

The macOS host can build both iOS and Android app, so I added it in case. I think we can remove it.

**Comment by anhappdev** [comment]
@freedomtan I got this error building for Android TFLite backend. Is there any installation / setup step needed except setting the env vars above?

```
$ make flutter/android
WITH_TFLITE=1
Skip checksum validation
bazel    \
                build --disk_cache=/Users/anh/cache/bazel --symlink_prefix bazel-  \
                --config=android_arm64 \
                //mobile_back_tflite/cpp/backend_tflite:libtflitebackend.so \
                 \
                 \
                 \
                 \
                //flutter/cpp/flutter:libbackendbridge.so
INFO: Invocation ID: 8c898bae-9bed-4b56-a492-33a1db4511d3
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=199
INFO: Reading rc options for 'build' from /Users/anh/dev/mlcommons/mobile_app_open/.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Reading rc options for 'build' from /Users/anh/dev/mlcommons/mobile_app_open/.bazelrc:
  'build' options: -c opt --announce_rc --config=short_logs --verbose_failures --spawn_strategy=standalone
INFO: Found applicable config definition build:short_logs in file /Users/anh/dev/mlcommons/mobile_app_open/.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:android_arm64 in file /Users/anh/dev/mlcommons/mobile_app_open/.bazelrc: --config=android --cpu=arm64-v8a --fat_apk_cpu=arm64-v8a
INFO: Found applicable config definition build:android in file /Users/anh/dev/mlcommons/mobile_app_open/.bazelrc: --copt=-w --cxxopt=-std=c++17 --host_cxxopt=-std=c++17 --crosstool_top=//external:android/crosstool --host_crosstool_top=@bazel_tools//tools/cpp:toolchain
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/llvm/llvm-project/archive/dc275fd03254d67d29cc70a5a0569acf24d2280d.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/tensorflow/runtime/archive/7d879c8b161085a4374ea481b93a52adb19c0529.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
WARNING: Download from https://mirror.bazel.build/github.com/bazelbuild/rules_cc/archive/081771d4a0e9d7d3aa0eed2ef389fa4700dfb23e.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/google/XNNPACK/archive/b9d4073a6913891ce9cbd8965c8d506075d2a45a.zip failed: class java.io.FileNotFoundException GET returned 404 Not Found
ERROR: /private/var/tmp/_bazel_anh/30b0ae0ebfc82d789f6eeabcb52f979d/external/local_config_cc/BUILD:44:19: in cc_toolchain_suite rule @local_config_cc//:toolchain: cc_toolchain_suite '@local_config_cc//:toolchain' does not contain a toolchain for cpu 'arm64-v8a'
ERROR: /private/var/tmp/_bazel_anh/30b0ae0ebfc82d789f6eeabcb52f979d/external/local_config_cc/BUILD:44:19: Analysis of target '@local_config_cc//:toolchain' failed
ERROR: Analysis of target '//flutter/cpp/flutter:libbackendbridge.so' failed; build aborted: 
INFO: Elapsed time: 3.718s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (247 packages loaded, 5944 targets configured)
make: *** [flutter/android/libs/build] Error 1

```

**Comment by freedomtan** [comment]
it seems you didn't set `ANDROID_NDK_API_LEVEL`.

> @freedomtan I got this error building for Android TFLite backend. Is there any installation / setup step needed except setting the env vars above and download the correct NDK version?
> 
> ```
> $ make flutter/android
> WITH_TFLITE=1
> Skip checksum validation
> bazel    \
>                 build --disk_cache=/Users/anh/cache/bazel --symlink_prefix bazel-  \
>                 --config=android_arm64 \
>                 //mobile_back_tflite/cpp/backend_tflite:libtflitebackend.so \
>                  \
>                  \
>                  \
>                  \
>                 //flutter/cpp/flutter:libbackendbridge.so
> INFO: Invocation ID: 8c898bae-9bed-4b56-a492-33a1db4511d3
> INFO: Options provided by the client:
>   Inherited 'common' options: --isatty=1 --terminal_columns=199
> INFO: Reading rc options for 'build' from /Users/anh/dev/mlcommons/mobile_app_open/.bazelrc:
>   Inherited 'common' options: --experimental_repo_remote_exec
> INFO: Reading rc options for 'build' from /Users/anh/dev/mlcommons/mobile_app_open/.bazelrc:
>   'build' options: -c opt --announce_rc --config=short_logs --verbose_failures --spawn_strategy=standalone
> INFO: Found applicable config definition build:short_logs in file /Users/anh/dev/mlcommons/mobile_app_open/.bazelrc: --output_filter=DONT_MATCH_ANYTHING
> INFO: Found applicable config definition build:android_arm64 in file /Users/anh/dev/mlcommons/mobile_app_open/.bazelrc: --config=android --cpu=arm64-v8a --fat_apk_cpu=arm64-v8a
> INFO: Found applicable config definition build:android in file /Users/anh/dev/mlcommons/mobile_app_open/.bazelrc: --copt=-w --cxxopt=-std=c++17 --host_cxxopt=-std=c++17 --crosstool_top=//external:android/crosstool --host_crosstool_top=@bazel_tools//tools/cpp:toolchain
> WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/llvm/llvm-project/archive/dc275fd03254d67d29cc70a5a0569acf24d2280d.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
> WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/tensorflow/runtime/archive/7d879c8b161085a4374ea481b93a52adb19c0529.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
> WARNING: Download from https://mirror.bazel.build/github.com/bazelbuild/rules_cc/archive/081771d4a0e9d7d3aa0eed2ef389fa4700dfb23e.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
> WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/google/XNNPACK/archive/b9d4073a6913891ce9cbd8965c8d506075d2a45a.zip failed: class java.io.FileNotFoundException GET returned 404 Not Found
> ERROR: /private/var/tmp/_bazel_anh/30b0ae0ebfc82d789f6eeabcb52f979d/external/local_config_cc/BUILD:44:19: in cc_toolchain_suite rule @local_config_cc//:toolchain: cc_toolchain_suite '@local_config_cc//:toolchain' does not contain a toolchain for cpu 'arm64-v8a'
> ERROR: /private/var/tmp/_bazel_anh/30b0ae0ebfc82d789f6eeabcb52f979d/external/local_config_cc/BUILD:44:19: Analysis of target '@local_config_cc//:toolchain' failed
> ERROR: Analysis of target '//flutter/cpp/flutter:libbackendbridge.so' failed; build aborted: 
> INFO: Elapsed time: 3.718s
> INFO: 0 processes.
> FAILED: Build did NOT complete successfully (247 packages loaded, 5944 targets configured)
> make: *** [flutter/android/libs/build] Error 1
> ```

**Comment by anhappdev** [comment]
I updated the docs and Docker container in this PR https://github.com/mlcommons/mobile_app_open/pull/788

Building the backend for TFLite, MediaTek, Pixel works, but not for Samsung and QTI, therefore the `App Build / build-android-apk` still fails.

**Comment by freedomtan** [comment]
> I updated the docs and Docker container in this PR #788
> 
> Building the backend for TFLite, MediaTek, Pixel works, but not for Samsung and QTI, therefore the `App Build / build-android-apk` still fails.

It seems we have some hard-coded library places, which do work because of changes of the NDK directory structure, in QTI backend. 

I guess if we change NDK back to r21, it will work. @mohitmundhragithub please help make NDK r25c work.

**Comment by anhappdev** [comment]
Build for Windows still failed.

**Comment by freedomtan** [comment]
@AhmedTElthakeb please help check if we build samsung backend with NDK 25c

**Comment by mohitmundhragithub** [comment]
can we merge #799 before this?

**Comment by freedomtan** [comment]
> can we merge #799 before this?

I am fine with that.

**Comment by mohitmundhragithub** [comment]
> > can we merge #799 before this?
> 
> I am fine with that.

Created #803 which has qti backend related changes, and also the changes in flutter required for fetching the libc++_shared.so from the ndk directly.

**Comment by freedomtan** [comment]
@anhappdev I fixed the Windows build. It's a stupid bug :-) Let's try to fix other issues.

**Comment by anhappdev** [comment]
The app now can be built successfully with all backends. 
Only the `Code Analysis` failed at the last scan step, but it's an issue of the code scanner. I will try to fix that later.

**Review by anhappdev — APPROVED** [review]

**Comment by freedomtan** [comment]
@AhmedTElthakeb and @mjkim010 you can get apk from https://github.com/mlcommons/mobile_app_open/actions/runs/6620173841?pr=787

**Comment by freedomtan** [comment]
on Samsung backend, link to the libc++_shared.so need to be updated, #812.

@freedomtan to check if adding the libc++_shared.so is necessary.

**Comment by freedomtan** [comment]
@AhmedTElthakeb and @anhappdev: it seems to me linking `libc++_share.so` is fine. Accutally, it should be required to specify which c++ library we want to use when building stuff with NDK for Android (because there is no stable C++ API). I cannot figure out why linking `libc++_shared.so` was not required for Samsung before (maybe some Samsung binaries / libraries did something like static link?)

**Review by anhappdev — APPROVED** [review]

**Review by Mostelk — APPROVED** [review]

**Pull request merged**
