### PR TITLE
chore: remove manage all file permission

### LINKED ISSUE #702: Check if we can get rid of manage all file permission
Currently, we have to manually enable the "Manage All Files Access Permission". That's not intuitive and could not be submit to Google Play Store.

https://github.com/mlcommons/mobile_app_open/pull/621

### PR DESCRIPTION
**Pull request by anhappdev**
- Closes #702

### CODE REVIEW

**Comment by freedomtan** [comment]
confirmed that this PR works for MediaTek internal devices.

**Comment by anhappdev** [comment]
> this PR worked for MediaTek internal devices except imagenet accuracy. dunno why yet.

Did you rename the file `imagenet_val_full.txt` to `imagenet_val_full.txt.pseudo.png`?

**Comment by freedomtan** [comment]
> > this PR worked for MediaTek internal devices except imagenet accuracy. dunno why yet.
> 
> Did you rename the file `imagenet_val_full.txt` to `imagenet_val_full.txt.pseudo.png`?

surely I did. For mobiledet + coco, it ran well. 

I tried it on my Pixel 7a, the app also crashed. See the attached logcat log [mobilenet_crash.txt](https://github.com/mlcommons/mobile_app_open/files/12074877/mobilenet_crash.txt)

**Comment by freedomtan** [comment]
If I use only the first 1000 `ILSVRC2012_val_000*.JPEG`, it works

**Comment by anhappdev** [comment]
Looking at the crash log, I guess maybe a file is corrupted.

**Comment by freedomtan** [comment]
> Looking at the crash log, I guess maybe an image file is corrupted.

with binary search, it shows `ILSVRC2012_val_00001644.JPEG` is incompatible with Android Exif related functions.
I am not sure if it's corrupted. It displayed well on both Android (with `File` app) and macOS Preview.
```
07-18 09:27:20.497  3254  5045 W System.err: java.lang.NumberFormatException: For input string: "????"
07-18 09:27:20.498  3254  5045 W System.err:    at java.lang.Integer.parseInt(Integer.java:747)
07-18 09:27:20.498  3254  5045 W System.err:    at java.lang.Integer.parseInt(Integer.java:865)
07-18 09:27:20.498  3254  5045 W System.err:    at android.media.ExifInterface$ExifAttribute.getIntValue(ExifInterface.java:1010)
07-18 09:27:20.498  3254  5045 W System.err:    at android.media.ExifInterface.handleThumbnailFromJfif(ExifInterface.java:4328)
07-18 09:27:20.498  3254  5045 W System.err:    at android.media.ExifInterface.setThumbnailData(ExifInterface.java:4301)
07-18 09:27:20.498  3254  5045 W System.err:    at android.media.ExifInterface.loadAttributes(ExifInterface.java:2033)
07-18 09:27:20.498  3254  5045 W System.err:    at android.media.ExifInterface.<init>(ExifInterface.java:1568)
07-18 09:27:20.498  3254  5045 W System.err:    at com.android.providers.media.MediaProvider.getRedactionRanges(MediaProvider.java:9050)
07-18 09:27:20.498  3254  5045 W System.err:    at com.android.providers.media.MediaProvider.getRedactionRanges(MediaProvider.java:9023)
07-18 09:27:20.498  3254  5045 W System.err:    at com.android.providers.media.MediaProvider.getRedactionRangesForFuse(MediaProvider.java:9005)
07-18 09:27:20.498  3254  5045 W System.err:    at com.android.providers.media.MediaProvider.onFileOpenForFuse(MediaProvider.java:9260)

```

I stripped EXIF information from the `ILSVRC2012_val_00001644.JPEG` file with exiftool, https://exiftool.org
```
exiftool -EXIF=  ILSVRC2012_val_00001644.JPEG 
```
and push it back to Android, then it went well.

I am not sure if there are other problematic ones.

**Comment by freedomtan** [comment]
@freedomtan to try to remove EXIF information from all the jpeg files which have EXIF to if we can finish reading all the 50, 000 imagenet validation files. < --- this doesn't look elegant. 

How MS office apps work on Android (do they use all file permission?)

**Comment by freedomtan** [comment]
```
for a in *.JPEG
  do exiftool -EXIF=  $a
done
```

**Comment by freedomtan** [comment]
> @freedomtan to try to remove EXIF information from all the jpeg files which have EXIF to if we can finish reading all the 50, 000 imagenet validation files. < --- this doesn't look elegant.
> 
> How MS office apps work on Android (do they use all file permission?) @freedomtan

Confirmed that 

- if I remove all the EXIF in jpeg files, I can get expected accuracy number on my Pixel 7a
- MS 365 apps DO need the "all file permission"

**Comment by freedomtan** [comment]
Let's try to see if we can get the apk accepted to Play Store with the "all file permission" option there. If that doesn't work, then we can to use this one.

**Comment by anhappdev** [comment]
The app is now accepted by Google for public testing at 
https://play.google.com/store/apps/details?id=org.mlcommons.android.mlperfbench

**Comment by freedomtan** [comment]
@anhappdev I didn't realize it's in "public testing" now. Could we back to "internal testing" because we don't have the EULA fixed and all the backends tested.

**Comment by anhappdev** [comment]
> @anhappdev I didn't realize it's in "public testing" now. Could we back to "internal testing" because we don't have the EULA fixed and all the backends tested.

Ok. Done.

**Comment by mohitmundhragithub** [comment]
I tried to run the app on my galaxy s23... but it crashes. Do we know of any known issues?

**Comment by anhappdev** [comment]
> I tried to run the app on my galaxy s23... but it crashes. Do we know of any known issues?

Can you test the [build 136](https://github.com/mlcommons/mobile_app_open/actions/runs/9204383464)? 
The `compileSdkVersion` was changed from 33 to 34 in that commit. Maybe that is the issue.

**Comment by freedomtan** [comment]
@mohitmundhragithub to test [build 136](https://github.com/mlcommons/mobile_app_open/actions/runs/9204383464) and [build 134](https://github.com/mlcommons/mobile_app_open/actions/runs/9202794767)

**Comment by mohitmundhragithub** [comment]
Hi @anhappdev @freedomtan,  I tried both build 134 and build 136 on my galaxy S23 ultra. Both of them are able to run the testcases just fine.

**Comment by anhappdev** [comment]
> I tried to run the app on my galaxy s23... but it crashes. Do we know of any known issues?

@mohitmundhragithub Can you share the crash log?

**Comment by mohitmundhragithub** [comment]
> > I tried to run the app on my galaxy s23... but it crashes. Do we know of any known issues?
> 
> @mohitmundhragithub Can you share the crash log?

Looks like the app is not available in playstore anymore.

**Comment by anhappdev** [comment]
> > > I tried to run the app on my galaxy s23... but it crashes. Do we know of any known issues?
> > 
> > 
> > @mohitmundhragithub Can you share the crash log?
> 
> Looks like the app is not available in playstore anymore.

Can you test the AKP here in the CI.

**Comment by mohitmundhragithub** [comment]
> > > > I tried to run the app on my galaxy s23... but it crashes. Do we know of any known issues?
> > > 
> > > 
> > > @mohitmundhragithub Can you share the crash log?
> > 
> > 
> > Looks like the app is not available in playstore anymore.
> 
> @mohitmundhragithub Can you test the APK here in the CI?

I tried this apk: https://github.com/mlcommons/mobile_app_open/actions/runs/9476794795/artifacts/1592456513

which i got from here (this PR's CI): https://github.com/mlcommons/mobile_app_open/actions/runs/9476794795/job/26110387649?pr=745

This also works fine.

**Comment by anhappdev** [comment]
> Could play store put some restrictions which makes the app to fail?

I don’t know yet. But if the crash is not related to this PR. Let’s merge this, then we will have a new build in Play Store and we can test the Play Store build again.

**Comment by mohitmundhragithub** [comment]
> > Could play store put some restrictions which makes the app to fail?
> 
> I don’t know yet. But if the crash is not related to this PR. Let’s merge this, then we will have a new build in Play Store and we can test the Play Store build again.

I am fine with it. 
does it work for everyone else as well?

**Review by freedomtan — APPROVED** [review]

**Pull request merged**
