### PR TITLE
Refactor flutter/lib/backend

### PR DESCRIPTION
**Pull request by d-uzlov**
Part of https://github.com/mlcommons/mobile_app_open/issues/172

This is a separate PR for a small part of the refactoring to make merge conflicts less likely and reviews easier.

### CODE REVIEW

**Comment by anhappdev** [comment]
Got an error running `make flutter/android`

```
rm -rf flutter/android/app/src/main/jniLibs/arm64-v8a
mkdir -p flutter/android/app/src/main/jniLibs/arm64-v8a
cp -f \
		bazel-bin/mobile_back_tflite/cpp/backend_tflite/libtflitebackend.so \
		 \
		 \
		 \
		 \
		bazel-bin/flutter/cpp/flutter/libbackendbridge.so \
		flutter/android/app/src/main/jniLibs/arm64-v8a
chmod 777 --recursive flutter/android/app/src/main/jniLibs/arm64-v8a
chmod: --recursive: No such file or directory
make: *** [flutter/android/libs] Error 1
```

**Comment by d-uzlov** [comment]
Oh, I _love_ macOS and its console utilities from 1970s that don't recognize options with `--` prefix and force people to use one-letter alternatives (if they even have one, which they often don't). So _convenient_ and _readable_.

**Comment by d-uzlov** [comment]
@anhappdev, I fixed build issues on macos.

**Comment by anhappdev** [comment]
I got an error when trying to clear cache via Settings
```
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: LateInitializationError: Field '_manufacturerUtf8@771123192' has already been initialized.
#0      LateError._throwFieldAlreadyInitialized (dart:_internal-patch/internal_patch.dart:211:5)
#1      _manufacturerUtf8= (package:mlcommons_ios_app/backend/bridge/native.match.dart:31:26)
#2      initDeviceInfo (package:mlcommons_ios_app/backend/bridge/native.match.dart:54:3)
<asynchronous suspension>
#3      MiddleInterface.findMatchingBackend (package:mlcommons_ios_app/benchmark/benchmark.dart:76:5)
<asynchronous suspension>
#4      MiddleInterface.create (package:mlcommons_ios_app/benchmark/benchmark.dart:101:30)
<asynchronous suspension>
#5      BenchmarkState.loadResources (package:mlcommons_ios_app/benchmark/benchmark.dart:284:15)
<asynchronous suspension>
#6      BenchmarkState.clearCache (package:mlcommons_ios_app/benchmark/benchmark.dart:280:5)
<asynchronous suspension>
#7      _SettingsScreen.build.<anonymous closure> (package:mlcommons_ios_app/ui/settings_screen.dart:174:19)
<asynchronous suspension>
```

**Comment by d-uzlov** [comment]
@anhappdev, fixed.

**Comment by d-uzlov** [comment]
Hi, @anhappdev.
This PR is blocking me. Could you take another look?

**Comment by anhappdev** [comment]
Ok. I am reviewing this PR.
BTW, you can just create a new branch from this one and working on it, that should not block you.

**Review by anhappdev — CHANGES_REQUESTED** [review]
I think it's better to use underscore instead of point in file name to have the same styles as other files: `native_config.dart`, `native_match.dart`, `native_run.dart`.

**Review by anhappdev — APPROVED** [review]

**Pull request merged**
