### PR TITLE
Add UI pages for result history

### PR DESCRIPTION
**Pull request by d-uzlov**
Closes https://github.com/mlcommons/mobile_app_open/issues/320

### CODE REVIEW

**Comment by d-uzlov** [comment]
<details>

<summary>Screenshots</summary>

 
 

</details>

**Comment by freedomtan** [comment]
comment by @Mostelk: add mechanism to delete history

**Review by anhappdev — CHANGES_REQUESTED** [review]
1. It's not obvious that the user can tap on the benchmark table row to view the run details. Maybe we can make row text color blue? Or some other UI changes so it's clear that the row is tappable.
2. [Minor] It would be nice to have the app bar title of the `RunDetailsScreen` showing the benchmark name.

**Comment by d-uzlov** [comment]
I have added arrow icons into the table of benchmarks.

**Review by anhappdev — APPROVED** [review]

**Pull request merged**
