### PR TITLE
Set new code options for sonar scanner

### PR DESCRIPTION
**Pull request by anhappdev**
Set new code options for sonar scanner per this guide:
https://docs.sonarcloud.io/improving/new-code-definition/

### CODE REVIEW

**Comment by anhappdev** [comment]
I would choose `Previous version`.

**Comment by morphine00** [comment]
Ok, that should be set now. Also is there a way that you or someone from the mobile group can manage this instead of me? Would saves us both the time, you having to ask me and me being a carrier pigeon :)

What permissions on the repo are necessary so that I could hand off the SonarCloud settings?

**Comment by anhappdev** [comment]
For SonarCloud, I hope there is no more setting to change, since this one should be "set and forget". But you can assign me an admin role on SonarCloud if you want, since SonarCloud is just a code analysis tool, there is nothing to break.
For GitHub, I will email you when I need more permissions.

**Comment by morphine00** [comment]
Ok, I just granted you permissions on SonarCloud. That was particularly easy.

**Comment by anhappdev** [comment]
Thanks.

**Review by d-uzlov — APPROVED** [review]

**Pull request merged**
