### PR TITLE
Update app version to 2.0

### PR DESCRIPTION
**Pull request by d-uzlov**
Closes https://github.com/mlcommons/mobile_app_open/issues/254

### CODE REVIEW

**Review by freedomtan — COMMENTED** [review]
how about java/org/mlperf/inference/res/layout/activity_splash.xml

**Comment by d-uzlov** [comment]
@freedomtan it seems like this file does not affect the actual splash screen.
It contains `1.1.1` version number, but what I actually see on the splash screen when I build the app is `1.1.0`.
And after I changed the version in the AndroidManifest file the splash screen got updated to 2.0.0.

**Review by freedomtan — APPROVED** [review]
LGTM

**Comment by d-uzlov** [comment]
Android app overrides value on the splash screen:
https://github.com/mlcommons/mobile_app_open/blob/d67a6b64f2bd212a2f2076ea80a03440cfa904e6/android/java/org/mlperf/inference/activities/SplashActivity.java#L39-L40

**Pull request merged**
