### PR TITLE
Update tflite bazel

### PR DESCRIPTION
**Pull request by ptt2panda**
We'd like to use the latest Tensorflow, including a commit below for Pixel 6 and our upcoming devices.
https://github.com/tensorflow/tensorflow/commit/c2dddb8c961fb4b6688bffc737bed90c6e9339af#diff-d2c4b1ed45cb51ecfee22e33e840bb0e01a08747a1d49df5c0f563957d41f4df

Also update bazel as newer tflite require higher bazel version.

Please help us take a look.
@kcwu @freedomtan

### CODE REVIEW

**Comment by kcwu** [comment]
This overlaps with https://github.com/mlcommons/mobile_app_open/pull/358 . You probably need to remove it from this PR, otherwise they will conflict.

**Comment by ptt2panda** [comment]
Thanks, I intend to merge this after #358 , will update PR if conflict appears.

**Comment by mohitmundhragithub** [comment]
I don't think we need to update TF version of android-v2 branch, as it won't have any active development.

**Comment by ptt2panda** [comment]
Hi @mohitmundhragithub , sure, we can use the master branch instead.
Could you advice what is the right way to build flutter app from the master branch? 
We follow the Readme, but still cannot build successfully yet.

**Comment by anhappdev** [comment]
@ptt2panda Which issue did you encountered? You can also open a new issue to get help. Maybe our docs is not up-to-date.

**Comment by mohitmundhragithub** [comment]
I use docker to build flutter app with qti backend.
The command that i use is:
make WITH_QTI=1 docker/flutter/android/apk

**Comment by d-uzlov** [comment]
@ptt2panda 
Can we delete `update_tflite_bazel` and `android_burst_execution` branches or do you still need them?

**Comment by ptt2panda** [comment]
Let me delete it now.

**Pull request closed without merging**
