### PR TITLE
Fix missing error on windows

### PR DESCRIPTION
**Pull request by d-uzlov**
Closes https://github.com/mlcommons/mobile_app_open/issues/224

### CODE REVIEW

**Comment by anhappdev** [comment]
I don't have a Windows machine, so I cannot test this PR.

BTW, I think we should copy the whole `android/cpp` out of `android` folder to make the Flutter app independent of the Android app (this is one of the steps in https://github.com/mlcommons/mobile_app_open/issues/153) since the Android app will be deprecated soon. We have code duplicate for a short period until the Android app is deprecated, but we save us from all possible side effects when updating it for the Flutter app.

**Comment by freedomtan** [comment]
@shabanim please review it.

**Comment by freedomtan** [comment]
@carlosd-29 please review it

**Review by carlosd-29 — APPROVED** [review]
Tested and prints error message as expected.

**Pull request merged**
