### PR TITLE
refactor: make stable diffusion flow work with one sd model

### PR DESCRIPTION
**Pull request by RSMNYS**

### CODE REVIEW

**Comment by anhappdev** [comment]
@RSMNYS Please rebase your PR on master

**Review by anhappdev — APPROVED** [review]

**Comment by anhappdev** [comment]
@RSMNYS Can you post the download link to `sd_diffusion_model_dynamic.tflite` you used in this PR?

**Comment by RSMNYS** [comment]
@anhappdev  you can find them in last Freedom's comment here: 

https://github.com/mlcommons/mobile_model_closed/issues/3

Also uploaded them here:

https://www.dropbox.com/scl/fo/rqehmpc9nmodnbgi4m4m9/ALKjmfvp1q8b9RXLIvvOq_M?rlkey=49urr4zp5s2tnovj07h8lms2k&dl=0

**Comment by anhappdev** [comment]
@RSMNYS Thank you

**Pull request merged**
