### PR TITLE
Add CI test for Qualcomm backend

### PR DESCRIPTION
**Pull request by d-uzlov**
Closes https://github.com/mlcommons/mobile_app_open/issues/555

### CODE REVIEW

**Comment by d-uzlov** [comment]
Qualcomm test failed because of checksum validation fail.
Logs:
```
checksum validation fail: file: /storage/emulated/0/Android/data/org.mlcommons.android.mlperfbench/files/loaded_resources/github.com/mlcommons/mobile_models/raw/main/v2_0/SNPE/mobilenet_edgetpu_224_1.0_htp_batched.dlc
checksum validation fail: expected: d239e3a244da27137ca6dae27facff5a
checksum validation fail: real: 862ea4d7623c62d49153bad1a774217c
```

This is the following file:
https://github.com/mlcommons/mobile_models/blob/main/v2_0/SNPE/mobilenet_edgetpu_224_1.0_htp_batched.dlc

It's stored using Git LFS, but it doesn't seem to be a problem.
I downloaded the file manually, and I also get the `862ea4d7623c62d49153bad1a774217c` checksum.

**Comment by d-uzlov** [comment]
Other files seems to be fine.

**Comment by d-uzlov** [comment]
@mohitmundhragithub, could you take a look, please?
Is the checksum in the backend config wrong? Can I just update it?

**Comment by d-uzlov** [comment]
The test has crashed on all devices that I tested.
The error on Snapdragon 865 devices:
```
cpp/backend_qti/qti_backend_helper.cc:139 runtime 1 is not available on this platform
```
The error on Snapdragon 888 devices:
```
cpp/backend_qti/qti_backend_helper.cc:139 runtime 0 is not available on this platform
```

Here are relevant parts of the log from each device:
[Samsung Galaxy S20, SM-G981U1, Snapdragon 865.log](https://github.com/mlcommons/mobile_app_open/files/9899814/Samsung.Galaxy.S20.SM-G981U1.Snapdragon.865.log)
[Samsung Galaxy Z Flip 3, SM-F711U1, Snapdragon 888.log](https://github.com/mlcommons/mobile_app_open/files/9899815/Samsung.Galaxy.Z.Flip.3.SM-F711U1.Snapdragon.888.log)
[Samsung Galaxy Z Fold 3, SM-F926U1, Snapdragon 888.log](https://github.com/mlcommons/mobile_app_open/files/9899816/Samsung.Galaxy.Z.Fold.3.SM-F926U1.Snapdragon.888.log)
[Samsung Galaxy Z Fold2, SM-F916U1, Snapdragon 865.log](https://github.com/mlcommons/mobile_app_open/files/9899817/Samsung.Galaxy.Z.Fold2.SM-F916U1.Snapdragon.865.log)

Full logs can be obtained from Firebase if needed:
https://console.firebase.google.com/project/mobile-app-build-290400/testlab/histories/bh.28fc664f482f1345/matrices/5386548683847881925

**Comment by mohitmundhragithub** [comment]
Looks like these devices doesn't allow HTP access from "untrusted_app". I don't think these devices can be enabled unless the OEM (Samsung in this case) enables it.

10-31 01:33:34.368: E/audit(681): avc:  denied  { find } for interface=vendor.qti.hardware.dsp::IDspService sid=u:r:untrusted_app:s0:c51,c257,c512,c768 pid=25742 scontext=u:r:untrusted_app:s0:c51,c257,c512,c768

**Comment by mohitmundhragithub** [comment]
> @mohitmundhragithub, could you take a look, please? Is the checksum in the backend config wrong? Can I just update it?

sorry, i was away last week. We also got similar error for this particular file. It's ok to update.
But just wondering how did the checksum get updated in github.

**Comment by d-uzlov** [comment]
> sorry, i was away last week. We also got similar error for this particular file. It's ok to update.
> But just wondering how did the checksum get updated in github.

There were already an updated checksum for this file in a config for another file.
If I remember correctly, Qualcomm updated all checksums some time ago, because qti used to modify files, in some way, but it doesn't.
I guess the person who updated the checksums updated this file for a new SoC but forget to check if this file was also used in other configs, and nobody tested the app on older devices.

**Comment by freedomtan** [comment]
Since we hit a limitation of devices (and their software) on Firebase. Let's close this for now. We may reopen this when we find another CI solution (e.g., a physical one).

**Pull request closed without merging**
