### PR TITLE
feat: add Firebase Crashlytics

### LINKED ISSUE #772: Add crash reporting to Flutter app
We can add [Firebase Crashlytics](https://firebase.google.com/docs/crashlytics) to the Flutter app. 

> Firebase Crashlytics is a lightweight, realtime crash reporter that helps you track, prioritize, and fix stability issues that erode your app quality. Crashlytics saves you troubleshooting time by intelligently grouping crashes and highlighting the circumstances that lead up to them.

### PR DESCRIPTION
**Pull request by anhappdev**
- Closes #772

- There is a switch for the crash reporting in the setting screen (default to OFF):

  Screenshot 2023-08-29 at 16 17 56

- The crash report can be seen here (permission required):
https://console.firebase.google.com/u/0/project/mobile-app-build-290400/crashlytics

- With this PR, a Firebase project is required to build the app.

### CODE REVIEW

**Review by freedomtan — APPROVED** [review]

**Comment by freedomtan** [comment]
@freedomtan: to test if we can really the app with Internet connection disabled (with assets: models and datasets)
@AhmedTElthakeb: please help test if you can build the apk after this PR.

**Comment by freedomtan** [comment]
I tested on some Pixel devices. With assets downloaded (or preloaded), we don't need internet connect. It seems there is no suspecious traffic when Internet is on.

**Comment by freedomtan** [comment]
@mohitmundhragithub confirmed that after setting up a dummy firebase configuration file, building the apk goes well.

@AhmedTElthakeb: to test it.

**Comment by AhmedTElthakeb** [comment]
I built and tested with no problem

**Comment by freedomtan** [comment]
@AhmedTElthakeb to check if Samsung colleagues behind a firewall could build it.

**Comment by freedomtan** [comment]
When building it behind the firewall, we should do 

```diff
+++ b/flutter/android/app/build.gradle
@@ -59,6 +59,9 @@ android {
             // TODO: Add your own signing config for the release build.
             // Signing with the debug keys for now, so `flutter run --release` works.
             signingConfig signingConfigs.debug
+            firebaseCrashlytics {
+                mappingFileUploadEnabled false
+            }
         }
     }
```

Should we make this the default. 

@anhappdev will change it true when building in CI.

**Pull request merged**
