### PR TITLE
Move samsung check to C++ code

### PR DESCRIPTION
**Pull request by d-uzlov**
Closes https://github.com/mlcommons/mobile_app_open/issues/206

### CODE REVIEW

**Comment by d-uzlov** [comment]
@al-mahi @Mostelk 
Please, test the [build](https://github.com/mlcommons/mobile_app_open/issues/177) with this fix and approve this if it works as expected.

**Comment by freedomtan** [comment]
@Mostelk: the new Samsung backend may not need this. Let's postpone this till 2.0 submission integration.

**Comment by freedomtan** [comment]
check if new 2.0-based app work, if yes, we can close this.

**Comment by freedomtan** [comment]
done in https://github.com/mlcommons/mobile_app_open/pull/271?

**Comment by d-uzlov** [comment]
@freedomtan #271 is a PR to Android-specific branch.
This PR is for Flutter app.
But this PR is probably irrelevant at this point because Samsung decided to use only new backend for the Flutter app which doesn't have this issue.

**Comment by freedomtan** [comment]
close it for now.

**Pull request closed without merging**
