### PR TITLE
For Mobilenet V4 large

### PR DESCRIPTION
**Pull request by freedomtan**
Use Mobilenet V4 large for Image Classification V2.

### CODE REVIEW

**Comment by freedomtan** [comment]
@mohitmundhragithub I fixed a stupid bug for floating model. Please try again.

**Comment by mohitmundhragithub** [comment]
> @mohitmundhragithub I fixed a stupid bug for floating model. Please try again.

Thanks a lot @freedomtan to share this.

I have added one more commit to modify the input images required for Calibration set for PTQ. Please have look.
@Mostelk, IMHO this removes the need for the default normalization model.

**Comment by freedomtan** [comment]
@anhappdev For MobileNet EdgeTPU, the input tensor is 224x224x3; for newly introduced model, it's 384x384x3. What's the best way to have both them? Add new dataset type, e.g., imagenet_384?

**Comment by anhappdev** [comment]
> @anhappdev For MobileNet EdgeTPU, the input tensor is 224x224x3; for newly introduced model, it's 384x384x3. What's the best way to have both them? Add new dataset type, e.g., imagenet_384? Or, we should add width and height paramters?

Where should we have both of them? Do you mean the `image_segmentation_v2` task should have multiple models with different input sizes?

There is already an `image_width` and `image_height` parameter in ModelConfig.
https://github.com/mlcommons/mobile_app_open/blob/e02bdc84c8090d78fdd3d8669fc2cd2869f5a929/flutter/cpp/proto/mlperf_task.proto#L95-L108

I

**Comment by freedomtan** [comment]
> > @anhappdev For MobileNet EdgeTPU, the input tensor is 224x224x3; for newly introduced model, it's 384x384x3. What's the best way to have both them? Add new dataset type, e.g., imagenet_384? Or, we should add width and height paramters?
> 
> Where should we have both of them? Do you mean the `image_classification_v2` task should have multiple models with different input sizes?
> 

nope, `image_classification` and `image_classification_v2` have different sizes.

> There is already an `image_width` and `image_height` parameter in ModelConfig.
> 
> https://github.com/mlcommons/mobile_app_open/blob/e02bdc84c8090d78fdd3d8669fc2cd2869f5a929/flutter/cpp/proto/mlperf_task.proto#L95-L108
> 
> I

We hard-coded image size for imagenet dataset at https://github.com/mlcommons/mobile_app_open/blob/master/flutter/cpp/flutter/dart_run_benchmark.cc#L73-L77

```c++
  switch (in->dataset_type) {
    case ::mlperf::mobile::DatasetConfig::IMAGENET:
      dataset = std::make_unique<::mlperf::mobile::Imagenet>(
          backend.get(), in->dataset_data_path, in->dataset_groundtruth_path,
          in->dataset_offset, 224, 224 /* width, height */);
      break;
...
```

**Comment by anhappdev** [comment]
> We hard-coded image size for imagenet dataset at ...

In that case, we just need to update the code to read the image size from the task file?

**Comment by freedomtan** [comment]
> > We hard-coded image size for imagenet dataset at ...
> 
> In that case, we just need to update the code to read the image size from the task file?

Yes, that's a better solution. A dirty hack is to add something like `case ::mlperf::mobile::DatasetConfig::IMAGENET_384:`
```C++
  switch (in->dataset_type) {
    case ::mlperf::mobile::DatasetConfig::IMAGENET:
      dataset = std::make_unique<::mlperf::mobile::Imagenet>(
          backend.get(), in->dataset_data_path, in->dataset_groundtruth_path,
          in->dataset_offset, 224, 224 /* width, height */);
      break;
```

**Comment by anhappdev** [comment]
> Yes, that's a better solution. 
> How to update our code to pass width and height to the  dart_ffi_run_benchmark_out* dart_ffi_run_benchmark in
https://github.com/mlcommons/mobile_app_open/blob/master/flutter/cpp/flutter/dart_run_benchmark.cc

I can send a PR to pass `image_width` and `image_height` to `dart_ffi_run_benchmark`. It requires code changes in multiple places.

**Comment by anhappdev** [comment]
@freedomtan Can you rebase this PR on the `719/new-edge-tpu-model` and also change this PR to merge into `719/new-edge-tpu-model` instead of `master`? I just updated `719/new-edge-tpu-model` with the latest commits from master.

**Comment by freedomtan** [comment]
> @freedomtan Can you rebase this PR on the `719/new-edge-tpu-model` and also change this PR to merge into `719/new-edge-tpu-model` instead of `master`? I just updated `719/new-edge-tpu-model` with the latest commits from master.

sure, I'll do it.

**Comment by anhappdev** [comment]
* https://github.com/mlcommons/mobile_app_open/pull/853/

**Comment by anhappdev** [comment]
TODO:

- [ ] Accuracy on Core ML is zero (iOS Build & Test / Build and test iOS app)

**Comment by anhappdev** [comment]
@freedomtan The original EdgeTPU-v2-L model at https://tfhub.dev/google/edgetpu/vision/mobilenet-edgetpu-v2/l/1 can only process images with size `224x224`. Where can I get a model or conversion script which works with image size `384x384`?

**Comment by freedomtan** [comment]
> @freedomtan The original EdgeTPU-v2-L model at https://tfhub.dev/google/edgetpu/vision/mobilenet-edgetpu-v2/l/1 can only process images with size `224x224`. Where can I get a model or conversion script which works with image size `384x384`?
> 
> This script does not work if I change the size from `224x224` to `384x384`: https://github.com/mlcommons/mobile_app_open/blob/332079f87adc132072955516df455aaeeb221a43/mobile_back_apple/models/icv2.py

@colbybanbury uploaded MobileNet V4 just now, https://github.com/mlcommons/mobile_open/releases/tag/model_upload

**Comment by anhappdev** [comment]
> @colbybanbury uploaded MobileNet V4 just now, see mlcommons/mobile_open#35 and https://github.com/mlcommons/mobile_open/releases/tag/model_upload. FP32 ones are too large, so they are in release.

@freedomtan Got it working now. 
I somehow edited your comment instead of replying as a new comment. Sorry for that, just undo it.

**Comment by freedomtan** [comment]
@RSMNYS The CoreML model for MobilenetV4 Large converted TensorFlow doesn't performance as good as as expected, this could be used a case for optimization CoreML models.

**Comment by freedomtan** [comment]
@anhappdev Any comments of how to the 6 failed tests?

**Comment by freedomtan** [comment]
- [x] Pixel backend: Tested on my Pixel 7 Pro
- [ ] tflite fallback
- [ ] MTK Neuron 
- [ ] iOS CoreML

**Comment by anhappdev** [comment]
> @anhappdev Any comments of how to the 6 failed tests?

They mostly failed on expected accuracy or throughput. I will run them several times and update the expected values.

**Comment by anhappdev** [comment]
Currently, the `test-android-apk-tflite` and `test-android-apk-pixel` failed because accuracy is always 0.0.
I don't have a Pixel device to debug this. @freedomtan Can you take a look and run the test locally (with `make flutter/test` cmd) with your devices to test?

**Comment by freedomtan** [comment]
> flutter/test

sometimes it failed, sometimes all tests passed

tested on Pixel 7 Pro running latest Android 14.

**Comment by freedomtan** [comment]
Let's test the TFLite backend on more devices to see if we can figure out why we got accuracy equals 0 on Pixel 5.

**Comment by freedomtan** [comment]
On a Samsung Galaxy S22+ (Exynos 2200), with TFLite backend only, I got expected accuracy numbers.

**Comment by freedomtan** [comment]
> Pixel backend:
> 
> * image_classification_v2:
>   
>   * Pixel 6, API Level 33 > accuracy OK
>   * Pixel 6, API Level 32 > accuracy OK
>   * Pixel 6, API Level 31 > accuracy OK
> * image_classification_offline_v2:
>   
>   * Pixel 6, API Level 33 > accuracy Zero
>   * Pixel 6, API Level 32 > accuracy Zero
>   * Pixel 6, API Level 31 > crash
> 
> TFLite backend:
> 
> * image_classification_v2:
>   
>   * Pixel 6, API Level 33 > accuracy OK
>   * Pixel 6, API Level 32 > accuracy OK
>   * Pixel 6, API Level 31 > accuracy OK
>   * Pixel 5, API Level 30 > accuracy Zero
> * image_classification_offline_v2:
>   
>   * Pixel 6, API Level 33 > accuracy OK
>   * Pixel 6, API Level 32 > accuracy OK
>   * Pixel 6, API Level 31 > accuracy OK
>   * Pixel 5, API Level 30 > accuracy Zero

That's interesting. I guess for Pixel backend + image_classification_offline_v2, we can get expected accuracy by reducing batch size.

For Pixel 5, either API level or other software stack issues?

**Comment by anhappdev** [comment]
> For Pixel 5, either API level or other software stack issues?

The Pixel 5 on Firebase Test Lab has only API Level 30 available, so I cannot test it with other API levels.
I tested on Motorola G20, API Level 30, TFLite backend > the accuracy is OK.
So I guess the issue is something specific to Pixel 5.

**Comment by RSMNYS** [comment]
> @RSMNYS The CoreML model for MobilenetV4 Large converted TensorFlow doesn't performance as good as as expected, this could be used a case for optimizing CoreML models.

@freedomtan  is this model the one we need to work with: https://github.com/mlcommons/mobile_open/raw/main/vision/mobilenetV4

**Comment by freedomtan** [comment]
> > @RSMNYS The CoreML model for MobilenetV4 Large converted TensorFlow doesn't performance as good as as expected, this could be used a case for optimizing CoreML models.
> 
> @freedomtan is this model the one we need to work with: https://github.com/mlcommons/mobile_open/raw/main/vision/mobilenetV4?
> 
> or this savedModel: https://github.com/mlcommons/mobile_open/releases/tag/model_upload?

Either one, or say, neither of them. We convert from the saved_model to CoreML model. The performance of the converted CoreML model is not as good as expected.  Please check how we can get a better CoreML model from either tflite of saved_model.

**Comment by RSMNYS** [comment]
> > > @RSMNYS The CoreML model for MobilenetV4 Large converted TensorFlow doesn't performance as good as as expected, this could be used a case for optimizing CoreML models.
> > 
> > 
> > @freedomtan is this model the one we need to work with: https://github.com/mlcommons/mobile_open/raw/main/vision/mobilenetV4?
> > or this savedModel: https://github.com/mlcommons/mobile_open/releases/tag/model_upload?
> 
> Either one, or say, neither of them. We convert from the saved_model to CoreML model. The performance of the converted CoreML model is not as good as expected. Please check how we can get a better CoreML model from either tflite of saved_model.

@freedomtan  are we expecting to have the MobilenetV4 performance on the task image_classification_V2 similar as for the https://github.com/mlcommons/mobile_models/raw/main/v3_0/CoreML/MobilenetEdgeTPU.mlmodel which Is used for the image_classification task (currently near 1000 qps)?

**Comment by freedomtan** [comment]
> > > > @RSMNYS The CoreML model for MobilenetV4 Large converted TensorFlow doesn't performance as good as as expected, this could be used a case for optimizing CoreML models.
> > > 
> > > 
> > > @freedomtan is this model the one we need to work with: https://github.com/mlcommons/mobile_open/raw/main/vision/mobilenetV4?
> > > or this savedModel: https://github.com/mlcommons/mobile_open/releases/tag/model_upload?
> > 
> > 
> > Either one, or say, neither of them. We convert from the saved_model to CoreML model. The performance of the converted CoreML model is not as good as expected. Please check how we can get a better CoreML model from either tflite of saved_model.
> 
> @freedomtan are we expecting to have the MobilenetV4 performance on the task image_classification_V2 similar as for the https://github.com/mlcommons/mobile_models/raw/main/v3_0/CoreML/MobilenetEdgeTPU.mlmodel which Is used for the image_classification task (currently near 1000 qps)?

as far as I can tell, 1000 qps is too good to be true for Mobilenet V4 Large. But 300 qps should be possible, I guess.

**Pull request merged**
