### PR TITLE
[v4.0] feat: add new tasks for image classification v2

### LINKED ISSUE #719: add single stream and offlline task for MNEdgeTPU-V2-L
We want replace MobileNet EdgeTPU with [MobileNet EdgeTPU-V2-L](https://github.com/tensorflow/models/tree/master/official/projects/edgetpu/vision#edgetpu-optimized-vision-models). Let's try have two more tasks at the main screen.  Let's create a new branch to see if 8 tasks are too crowded.

We need both fp and qint8 tflite files (@Mostelk to add the links to tflite files)
fp: from the tf-model site
quint: from tf-hub

### PR DESCRIPTION
**Pull request by anhappdev**
Closes #719 

This is how the app looks with 2 new tasks:

### CODE REVIEW

**Comment by freedomtan** [comment]
version name scheme: should we call it Classification V2 (after model name) or V3.1 (align with the app version)? Let's discuss this in main mobile working group.

**Comment by freedomtan** [comment]
we can move the two mobilenet edgetpu models to the end of the list later

**Comment by freedomtan** [comment]
Let's call it V2 (not V2.0).

**Comment by anhappdev** [comment]
The accuracy test of `image_classification_offline_v2` failed on Pixel 6 with Pixel backend because the accuracy is 0.
But `image_classification_v2` on Pixel 6 passed the test.
Other backends (TFLite, Core ML) also passed the test.

@freedomtan Do you have an idea what can be the reason for this?

**Comment by freedomtan** [comment]
> The accuracy test of `image_classification_offline_v2` failed on Pixel 6 with Pixel backend because the accuracy is 0. But `image_classification_v2` on Pixel 6 passed the test. Other backends (TFLite, Core ML) also passed the test.
> 
> @freedomtan Do you have an idea what can be the reason for this?

Yes, I ran into the same problem on Pixel 7 before. It seems you have to reduce the batch size to a much smaller one. I guess it’s a bug or limitation of EdgeTPU.

**Comment by anhappdev** [comment]
> Yes, I ran into the same problem on Pixel 7 before. It seems you have to reduce the batch size to a much smaller one. I guess it’s a bug or limitation of EdgeTPU.

Thank you. Reducing the batch size worked.

**Comment by freedomtan** [comment]
let's rebase this one and create an 4.0 branch.

**Comment by freedomtan** [comment]
Let's rebase this to current master branch and make the model path local (local://) and without checksum, so that it's easier to test new models (we may get more than one model to test).

**Comment by anhappdev** [comment]
@freedomtan 
> Let's rebase this to current master branch 

Done

> and make the model path local (local://) and without checksum, so that it's easier to test new models (we may get more than one model to test).

Each vendor should add a new `benchmark_setting` to its setting file like this, and can set its own path to local for testing.

```pbtxt
benchmark_setting {
  benchmark_id: "image_classification_v2"
  framework: "TFLite"
  delegate_choice: {
    delegate_name: "CPU"
    accelerator_name: "cpu"
    accelerator_desc: "CPU"
    model_path: "https://github.com/mlcommons/mobile_models/raw/anh/add-MNEdgeTPU-V2-L/v3_1/tflite/mobilenet-edgetpu-v2-L_fp32.tflite"
    model_checksum: "4b7ce0a82f8eaa542404d2ab2ee4e575"
  }
}

benchmark_setting {
  benchmark_id: "image_classification_offline_v2"
  framework: "TFLite"
  delegate_choice: {
    delegate_name: "CPU"
    accelerator_name: "cpu"
    accelerator_desc: "CPU"
    batch_size: 2
    model_path: "https://github.com/mlcommons/mobile_models/raw/anh/add-MNEdgeTPU-V2-L/v3_1/tflite/mobilenet-edgetpu-v2-L_fp32.tflite"
    model_checksum: "4b7ce0a82f8eaa542404d2ab2ee4e575"
  }
}
```

Or should I remove the checksum and set the path to local for `tflite_settings_android.pbtxt`?

**Comment by freedomtan** [comment]
> @freedomtan
> 
> > Let's rebase this to current master branch
> 
> Done
> 
we need `max_duration` for new benchmark items.

```diff
diff --git a/flutter/assets/tasks.pbtxt b/flutter/assets/tasks.pbtxt
index 5a113ca..d7cf0be 100644
--- a/flutter/assets/tasks.pbtxt
+++ b/flutter/assets/tasks.pbtxt
@@ -221,6 +221,7 @@ task {
   name: "Image Classification v2"
   min_query_count: 1024
   min_duration: 60
+  max_duration: 600
   max_throughput: 1000
   max_accuracy: 1.0
   scenario: "SingleStream"
@@ -257,6 +258,7 @@ task {
   name: "Image Classification v2 (Offline)"
   min_query_count: 24576
   min_duration: 0
+  max_duration: 600
   max_throughput: 2000
   max_accuracy: 1.0
   scenario: "Offline"
```

**Comment by anhappdev** [comment]
> we need max_duration for new benchmark items.

Done. `max_duration` does not work in Offline scenario, so I set it to zero.

**Comment by freedomtan** [comment]
@mohitmundhragithub and @AhmedTElthakeb for some new models, we need different preprocessing, I have a hack based on this one,  https://github.com/mlcommons/mobile_app_open/commit/1d9e1e9aed2008754d5749b702380df67a1e2af6

**Comment by mohitmundhragithub** [comment]
> @mohitmundhragithub and @AhmedTElthakeb for some new models, we need different preprocessing, I have a hack based on this one, [1d9e1e9](https://github.com/mlcommons/mobile_app_open/commit/1d9e1e9aed2008754d5749b702380df67a1e2af6)

this is for which model? 
I think MobileNetEdgeTPUv2 model was working fine... no?

**Comment by freedomtan** [comment]
@freedomtan to send PRs for different input sizes for new models (with different preprocessing). 224x224, 256x256, 384x384

**Comment by anhappdev** [comment]
To check why `iOS Tests` and `android-test-pixel` failed with `no matching backend found`.

**Review by freedomtan — APPROVED** [review]

**Comment by anhappdev** [comment]
Should we merge this to `submission-v4.0` branch first? And then after the submission, we merge `submission-v4.0` into `master`.

**Comment by freedomtan** [comment]
> Should we merge this to `submission-v4.0` branch first? And then after the submission, we merge `submission-v4.0` into `master`.

I am fine with either way. Let's discuss it in the meeting.

**Comment by freedomtan** [comment]
1. let's merge this to submission-v4.0 first, and back to master when we have good qualcomm backend for the classification V2.
2. change order of test as @mohitmundhragithub suggested.

**Pull request merged**
