### PR TITLE
QTI submission for MLPerf V3.0

### PR DESCRIPTION
**Pull request by mohitmundhragithub**
Devices submitted: SD8G2, SD7PG2, SD8CXG3

Co-authored by: Aasheesh Tiwari <quic_aasheesh@quicinc.com>
Co-authored-by: Mohit Mundhra <quic_mmundhra@quicinc.com>
Co-authored-by: Utkarsh Mirshra <quic_utkarshm@quicinc.com>

### CODE REVIEW

**Comment by mohitmundhragithub** [comment]
@anhappdev , I don't have permission to see the windows build failure. Can you please help with the logs for the same?
Meanwhile, i will look into the security issues.

**Comment by anhappdev** [comment]
[The log is here](https://ff9d4bb2d2be777be31ef45f8894f335b8740cd78cbeec066acd3fb-apidata.googleusercontent.com/download/storage/v1/b/338267405985.cloudbuild-logs.googleusercontent.com/o/log-abd9b08b-ebec-41b3-87bf-9233c53dca30.txt?jk=Ac_6HjI2YMdSnoVIhNdZZSpz5P7QedP_4g5oloTlert75Ip9jQYUmOWds0vrFtTiVgd4Qo6Pw2gCrfKPVvxdIoGXOnMvyKAUHPEWXMQ5pvaELzJ-wVN-KXpwclwhekonlhhP7C0IE1v9XTZeuVeN22GqBZ1nf5StOisRfsUgfktbOlnY-GD3GP6QtXn7l9nJMjh5nuHWpk7wNktJv2rf2hXnN8qbh_9tPrO4JM44btpZF9soGwGzfVCVsk2ke8hj082vGkBx_dXxkHA1IJbuHZSpg1i7vufpgLNtA0dl7g3WvkhsPwG3dxaF5494czXUcGOSzb7IENUYRYk379I_JNWOShcLi86hSrpFj3ah4IHEccHu0DLVEkTq2kOpyv4RK5A50GDwEiw6S5NCn_DW-wQT-pzwtGGj3H3-_Z9cr93X7F2ZoKbEqRDfXcgTquqVO_tLIU-AIYi-Kpj0UBak5Mq8WHCrk1LnJWymdXynW6uLfduTG9Z3QRwF9RETaIoRpPRHzi1UdjSui7ECZcUzWsZa_qlby3pYkHVXhgLxZn7A2z9DmwvWgY8Suyp0Dw1mFyHcuYjlgthGn6HFZEy057LYXLJkSQm3w3Ly9sGpkUCmIZFhV126PgpSnQsOnPJaH8M8AeZky846eLb764jCPbpIgnqbopf3pOtwfToXEcTYrHbdHLo_L7MNmcQbNRc8wG9_XnAgilgWV7UXpNOk7Fp4Mb0ikA4uHCxPA54B-abWN_ASAY9sn__cRB6W7pGocM6UXQpjIyfHauuzUoYYgkHoYgWFsexLBIlN2aTyZxA3CMzOtAqxwQRx_J3IBzuvqiKANZFz6-mza5vUR0b7LHDqU9wws2uaFaliQJX1LoTrlrVSXmgtkSxZVkuJ8nkd_LevLfOWR4vCK954qX7zCKvfJMod17-JGXq7Yx36VdDXL_HF5KBLOghh6lPVuW0uX2QjqFdCNcnEnjWwpM1pX2bi-fbogqMMof6s85_5fj7ekEpYeYLuTf8VsbnpMiZ0x8p4a_ld06v9UofTrCMjoLi7-Adrtf_cho_yEBV-Ap8zedPUwB4vZu6_Apk24EWTnPOV6z6M96FAxxLNFodg33JJdMc5VWHlBBub-fflHEmw9_VEWLtqAdkYCm_Oxne8q6AsjvNC0ldN9Etnhg2MB-ZDhmKuHUnLCb8KigY61ZU8qTDXQDeklryeMaYqkbV1_tywt332o2ie-ni3yO2rdfxiUhJKOt8WUCe7h6LvPA7BhtcYWmQkUUM4tEnSBxOJxEUo1z-p99lT6xXDfgfEz07LqvgmvXtWmuK-rhogmNGuSpETBde8HilvNMz9WFo&isca=1)

**Comment by mohitmundhragithub** [comment]
> [The log is here](https://ff9d4bb2d2be777be31ef45f8894f335b8740cd78cbeec066acd3fb-apidata.googleusercontent.com/download/storage/v1/b/338267405985.cloudbuild-logs.googleusercontent.com/o/log-abd9b08b-ebec-41b3-87bf-9233c53dca30.txt?jk=Ac_6HjI2YMdSnoVIhNdZZSpz5P7QedP_4g5oloTlert75Ip9jQYUmOWds0vrFtTiVgd4Qo6Pw2gCrfKPVvxdIoGXOnMvyKAUHPEWXMQ5pvaELzJ-wVN-KXpwclwhekonlhhP7C0IE1v9XTZeuVeN22GqBZ1nf5StOisRfsUgfktbOlnY-GD3GP6QtXn7l9nJMjh5nuHWpk7wNktJv2rf2hXnN8qbh_9tPrO4JM44btpZF9soGwGzfVCVsk2ke8hj082vGkBx_dXxkHA1IJbuHZSpg1i7vufpgLNtA0dl7g3WvkhsPwG3dxaF5494czXUcGOSzb7IENUYRYk379I_JNWOShcLi86hSrpFj3ah4IHEccHu0DLVEkTq2kOpyv4RK5A50GDwEiw6S5NCn_DW-wQT-pzwtGGj3H3-_Z9cr93X7F2ZoKbEqRDfXcgTquqVO_tLIU-AIYi-Kpj0UBak5Mq8WHCrk1LnJWymdXynW6uLfduTG9Z3QRwF9RETaIoRpPRHzi1UdjSui7ECZcUzWsZa_qlby3pYkHVXhgLxZn7A2z9DmwvWgY8Suyp0Dw1mFyHcuYjlgthGn6HFZEy057LYXLJkSQm3w3Ly9sGpkUCmIZFhV126PgpSnQsOnPJaH8M8AeZky846eLb764jCPbpIgnqbopf3pOtwfToXEcTYrHbdHLo_L7MNmcQbNRc8wG9_XnAgilgWV7UXpNOk7Fp4Mb0ikA4uHCxPA54B-abWN_ASAY9sn__cRB6W7pGocM6UXQpjIyfHauuzUoYYgkHoYgWFsexLBIlN2aTyZxA3CMzOtAqxwQRx_J3IBzuvqiKANZFz6-mza5vUR0b7LHDqU9wws2uaFaliQJX1LoTrlrVSXmgtkSxZVkuJ8nkd_LevLfOWR4vCK954qX7zCKvfJMod17-JGXq7Yx36VdDXL_HF5KBLOghh6lPVuW0uX2QjqFdCNcnEnjWwpM1pX2bi-fbogqMMof6s85_5fj7ekEpYeYLuTf8VsbnpMiZ0x8p4a_ld06v9UofTrCMjoLi7-Adrtf_cho_yEBV-Ap8zedPUwB4vZu6_Apk24EWTnPOV6z6M96FAxxLNFodg33JJdMc5VWHlBBub-fflHEmw9_VEWLtqAdkYCm_Oxne8q6AsjvNC0ldN9Etnhg2MB-ZDhmKuHUnLCb8KigY61ZU8qTDXQDeklryeMaYqkbV1_tywt332o2ie-ni3yO2rdfxiUhJKOt8WUCe7h6LvPA7BhtcYWmQkUUM4tEnSBxOJxEUo1z-p99lT6xXDfgfEz07LqvgmvXtWmuK-rhogmNGuSpETBde8HilvNMz9WFo&isca=1)

this log is not accessible. Can you please share somewhere else? or attach the text file?

**Comment by anhappdev** [comment]
> > [The log is here](https://ff9d4bb2d2be777be31ef45f8894f335b8740cd78cbeec066acd3fb-apidata.googleusercontent.com/download/storage/v1/b/338267405985.cloudbuild-logs.googleusercontent.com/o/log-abd9b08b-ebec-41b3-87bf-9233c53dca30.txt?jk=Ac_6HjI2YMdSnoVIhNdZZSpz5P7QedP_4g5oloTlert75Ip9jQYUmOWds0vrFtTiVgd4Qo6Pw2gCrfKPVvxdIoGXOnMvyKAUHPEWXMQ5pvaELzJ-wVN-KXpwclwhekonlhhP7C0IE1v9XTZeuVeN22GqBZ1nf5StOisRfsUgfktbOlnY-GD3GP6QtXn7l9nJMjh5nuHWpk7wNktJv2rf2hXnN8qbh_9tPrO4JM44btpZF9soGwGzfVCVsk2ke8hj082vGkBx_dXxkHA1IJbuHZSpg1i7vufpgLNtA0dl7g3WvkhsPwG3dxaF5494czXUcGOSzb7IENUYRYk379I_JNWOShcLi86hSrpFj3ah4IHEccHu0DLVEkTq2kOpyv4RK5A50GDwEiw6S5NCn_DW-wQT-pzwtGGj3H3-_Z9cr93X7F2ZoKbEqRDfXcgTquqVO_tLIU-AIYi-Kpj0UBak5Mq8WHCrk1LnJWymdXynW6uLfduTG9Z3QRwF9RETaIoRpPRHzi1UdjSui7ECZcUzWsZa_qlby3pYkHVXhgLxZn7A2z9DmwvWgY8Suyp0Dw1mFyHcuYjlgthGn6HFZEy057LYXLJkSQm3w3Ly9sGpkUCmIZFhV126PgpSnQsOnPJaH8M8AeZky846eLb764jCPbpIgnqbopf3pOtwfToXEcTYrHbdHLo_L7MNmcQbNRc8wG9_XnAgilgWV7UXpNOk7Fp4Mb0ikA4uHCxPA54B-abWN_ASAY9sn__cRB6W7pGocM6UXQpjIyfHauuzUoYYgkHoYgWFsexLBIlN2aTyZxA3CMzOtAqxwQRx_J3IBzuvqiKANZFz6-mza5vUR0b7LHDqU9wws2uaFaliQJX1LoTrlrVSXmgtkSxZVkuJ8nkd_LevLfOWR4vCK954qX7zCKvfJMod17-JGXq7Yx36VdDXL_HF5KBLOghh6lPVuW0uX2QjqFdCNcnEnjWwpM1pX2bi-fbogqMMof6s85_5fj7ekEpYeYLuTf8VsbnpMiZ0x8p4a_ld06v9UofTrCMjoLi7-Adrtf_cho_yEBV-Ap8zedPUwB4vZu6_Apk24EWTnPOV6z6M96FAxxLNFodg33JJdMc5VWHlBBub-fflHEmw9_VEWLtqAdkYCm_Oxne8q6AsjvNC0ldN9Etnhg2MB-ZDhmKuHUnLCb8KigY61ZU8qTDXQDeklryeMaYqkbV1_tywt332o2ie-ni3yO2rdfxiUhJKOt8WUCe7h6LvPA7BhtcYWmQkUUM4tEnSBxOJxEUo1z-p99lT6xXDfgfEz07LqvgmvXtWmuK-rhogmNGuSpETBde8HilvNMz9WFo&isca=1)
> 
> this log is not accessible. Can you please share somewhere else? or attach the text file?

Ok. Please see [log.txt](https://github.com/mlcommons/mobile_app_open/files/11144983/log.txt)

**Pull request closed without merging**
