### PR TITLE
Update Android compileSdkVersion and targetSdkVersion from 31 to 33

### LINKED ISSUE #586: Update Android compiler version
After we updated to Flutter v3.3.5 we started getting a warning that we should update Android compiler to v33.
Updating some of the Flutter lib dependencies transforms this warning into an error.

```
One or more plugins require a higher Android SDK version.
Fix this issue by adding the following to A:\work\git\mobile_app_open\flutter\android\app\build.gradle:
android {
  compileSdkVersion 33
  ...
}
```

### PR DESCRIPTION
**Pull request by anhappdev**
Closes #586

### CODE REVIEW

**Comment by anhappdev** [comment]
Unified APK for testing:
[2022-10-31_mlperfbench-1483e21-qsmgt_PR597.apk](https://drive.google.com/file/d/1BpwwntMcpBZHSmUfDLvY1N0vWKjJt6-t/view?usp=sharing)

Build cmd:
```
 make flutter/android/release \
  WITH_QTI=1 WITH_SAMSUNG=1 WITH_MEDIATEK=1 WITH_PIXEL=1 WITH_TFLITE=1 \
  OFFICIAL_BUILD=false FLUTTER_BUILD_NUMBER=0
```
QTI lib: `snpe-1.65.0.3676`
Samsung lib: [tree/submission_v2.1_samsung_backend](https://github.com/mlcommons/mobile_back_samsung/tree/submission_v2.1_samsung_backend/samsung_libs/mobile_back_samsung)

**Comment by freedomtan** [comment]
- [ ] Google, :
- [ ] MediaTek, Get expected performance numbers on some MediaTek internal devices and [Xiaomi Redmi K50 Pro ](https://www.gsmarena.com/xiaomi_redmi_k50_pro-11372.php). Reported by @freedomtan 
- [ ] QTI:
- [ ] Samsung:

**Comment by freedomtan** [comment]
@Mostelk this apk comes with the custom folder patch, #562

**Comment by freedomtan** [comment]
@anhappdev could you build another apk after merging https://github.com/mlcommons/mobile_app_open/pull/603

**Comment by anhappdev** [comment]
@AhmedTElthakeb Which branch from https://github.com/mlcommons/mobile_back_samsung/branches should I use to build the APK for this PR? Noted that the base branch I will use for this is the latest `master` branch.

**Pull request merged**
