### PR TITLE
[Do not merge] Update README.md

### PR DESCRIPTION
**Pull request by gellouglas**

### CODE REVIEW

**Comment by bellycat77** [comment]
ok for test

**Comment by bellycat77** [comment]
ok to test

**Comment by TheKanter** [comment]
Membership@mlcommons.org should be updated to participation@mlcommons.org

**Comment by mcharleb** [comment]
@bellycat77  Can we close this now that we have https://github.com/mlcommons/mobile_app_open/pull/62 ?

**Comment by bellycat77** [comment]
It was PR for testing CI purposes

**Pull request closed without merging**
