### PR TITLE
Update configs of vendor backends

### PR DESCRIPTION
**Pull request by d-uzlov**
Closes https://github.com/mlcommons/mobile_app_open/issues/322

### CODE REVIEW

**Review by anhappdev — APPROVED** [review]
LGTM. Please add vendor's engineers as reviewer so they acknowledge the change in backend settings.

**Review by freedomtan — APPROVED** [review]
LGTM. Tested on some MTK internal devices.

**Comment by freedomtan** [comment]
Note that currently we only test accuracy on Pixel devices on CI.

**Comment by d-uzlov** [comment]
I have split this PR into several smaller ones:
* https://github.com/mlcommons/mobile_app_open/pull/500
* https://github.com/mlcommons/mobile_app_open/pull/501
* https://github.com/mlcommons/mobile_app_open/pull/502
* https://github.com/mlcommons/mobile_app_open/pull/503

**Pull request closed without merging**
