### PR TITLE
Update Loadgen version

### PR DESCRIPTION
**Pull request by bellycat77**
Use Loadgen r1.1 branch commit 8a5b5db8df1dc8b6de6adfefe9fd96d918f53fb2

### CODE REVIEW

**Comment by relja128** [comment]
@bellycat77 - please run a performance test of new loadgen vs old loadgen to see if there are any performance differences

**Comment by bellycat77** [comment]
@relja128  results of performance benchmarking (Old, New, New, Old):
Screenshot 2021-08-31 at 19 10 56
Screenshot 2021-08-31 at 19 13 59
Screenshot 2021-08-31 at 19 15 12
Screenshot 2021-08-31 at 19 16 07

**Comment by bellycat77** [comment]
APKs:
with old loadgen: https://drive.google.com/file/d/1zoe9BUPLAer5V87Oj14V9n1DmqqqQb4J/view?usp=sharing
with new loadgen: https://drive.google.com/file/d/1qnt25Y90Sd5qZl6yOEKGBBBquu2YBDoq/view?usp=sharing

**Comment by relja128** [comment]
@mcharleb - can we take this?

**Comment by mcharleb** [comment]
I'll pull in the change and give it a test to see if I see any regression. The drop by 40% for IS in one of the tests concerns me but that could just be the variance for this backend.

**Comment by mcharleb** [comment]
@relja128  I tested with this new version and I see not change in the results, so yes we can take this.

**Review by willc2010 — APPROVED** [review]

**Comment by mcharleb** [comment]
@willc2010  I believe @relja128 said elsewhere that he wants to wait on merging this until after submission because of a new log reporting format.

**Pull request merged**
