### PR TITLE
Extend pixel backend to support all Google devices with edgetpu

### PR DESCRIPTION
**Pull request by kcwu**

### CODE REVIEW

**Comment by freedomtan** [comment]
@kcwu please contact @jwookiehong to get the CLA stuff done

**Comment by kcwu** [comment]
My CLA status should be good. Please review this PR.

**Comment by freedomtan** [comment]
@d-uzlov @anhappdev how to trigger check again without committing things?

**Comment by d-uzlov** [comment]
@freedomtan you can open the "Details" link and select `Rerun all jobs` in the top right corner.
I have triggered a rerun for the CLA check. it's green now.

**Review by freedomtan — APPROVED** [review]
LGTM

**Comment by freedomtan** [comment]
@d-uzlov will help remove `C++, bazel, java, and misc` tests so that we can merge.

**Pull request merged**
