### PR TITLE
feat: add user signup flow

### PR DESCRIPTION
**Pull request by anhappdev**
Part of #670

A user can either sign in anonymously or with email/password.
On the sign in with email/password screen, a user can also register for a new account.

To convert from an anonymous account to a registered account with email/password:

1. Tap on the User Profile button

2. Tap on the Email icon to enter an email and password

### CODE REVIEW

**Comment by anhappdev** [comment]
I am using [firebase_ui_auth](https://pub.dev/packages/firebase_ui_auth) which provides premade screens for user sign in and sign up flow. But this plugin does not support the Windows platform officially. I don't have experience with Windows or a Windows machine to test. So I am thinking either someone with Windows experience can jump in or maybe we can drop support for Windows (for now)?

**Comment by freedomtan** [comment]
@mohitmundhragithub to help with the Windows part

**Comment by freedomtan** [comment]
Currently there is no 3rd party authentication. We can add it later (in another PR)

**Comment by anhappdev** [comment]
I removed the Firebase SDK on the Windows platform. For now, Firebase will only be supported on iOS and Android.

**Comment by anhappdev** [comment]
@freedomtan Did you have the time to review this PR? This one currently blocks some other issues.

**Review by freedomtan — APPROVED** [review]

**Comment by freedomtan** [comment]
@anhappdev I cannot find the sign-in related menu items  when I built from  https://github.com/mlcommons/mobile_app_open/commit/84df7172d7ab3f17b8f0587d704f52314e16b284

**Comment by anhappdev** [comment]
@freedomtan If you build the app yourself, you need to follow this guide
https://github.com/mlcommons/mobile_app_open/blob/master/docs/environment-setup/env-setup-firebase.md
and set the vars in `firebase_options.env`. Else all Firebase related features will be hidden / disabled.

Or you can test the APK built by the CI, which has Firebase enabled.

**Pull request merged**
