### PR TITLE
Rename BenchmarkSetting's field configuration to framework for Pixel

### PR DESCRIPTION
**Pull request by anhappdev**
Part of #540

### CODE REVIEW

**Comment by anhappdev** [comment]
@ptt2panda Do you want to change anything in this PR or is it good to merge?

**Comment by ptt2panda** [comment]
@kcwu

**Comment by kcwu** [comment]
Pixel uses only NPU to execute those models, so it is unnecessary to mention GPU and DSP.

**Comment by anhappdev** [comment]
@kcwu Thanks for the feedback. I updated the text. Is there any change you want to make? Please approve the PR when you don't want to change anything else.

**Comment by kcwu** [comment]
Please describe it as
  accelerator = tpu
  accelerator_desc = Google Edge TPU
thanks

**Comment by anhappdev** [comment]
Done

**Review by kcwu — APPROVED** [review]

**Pull request merged**
