### PR TITLE
Do not force burst execution

### PR DESCRIPTION
**Pull request by ptt2panda**
@kcwu @freedomtan , please help review.

### CODE REVIEW

**Comment by kcwu** [comment]
LGTM.
@freedomtan I cannot use github's code review system. Could you help add me to the collaborator list of this project?

**Review by kcwu — DISMISSED** [review]
LGTM.
Oh, I found I can review actually. Sorry I'm not familiar with github's review system.

**Review by freedomtan — DISMISSED** [review]

**Comment by d-uzlov** [comment]
@kcwu could you please push a new commit to re-trigger iOS CI?
The error there seems completely unrelated to changes in the PR so I think it may fix itself on next run.

**Comment by ptt2panda** [comment]
Check is passed, @d-uzlov , could you help approve again? Thanks!

**Review by d-uzlov — APPROVED** [review]

**Comment by d-uzlov** [comment]
@ptt2panda please, use "Squash and merge" action to merge pull requests.
Non-linear commit history is much harder to read and navigate.

**Comment by anhappdev** [comment]
@d-uzlov Maybe we can force squash merging if it's desired?
https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/about-merge-methods-on-github

**Comment by ptt2panda** [comment]
Sorry about that, I was not aware of the  "Squash and merge".
I'll make sure to use that in the future PRs.

**Comment by d-uzlov** [comment]
@ptt2panda, no problem, it's just a bit inconvenient.

@anhappdev, oh, thank you, I didn't notice this option in settings.
I have set it up to only enable squash-and-merge merge method.

**Pull request merged**
