### PR TITLE
feat: add result download

### PR DESCRIPTION
**Pull request by anhappdev**
Part of #670 

When the app starts, it will query the list of online results in Firebase Storage under the same user ID, then download ones, which do not exist in local storage.

### CODE REVIEW

**Comment by anhappdev** [comment]
As listed in https://github.com/mlcommons/mobile_app_open/issues/670 the next PR will add the option to convert from an anonymous account to a normal account.

**Comment by freedomtan** [comment]
@freedomtan to test it

**Comment by anhappdev** [comment]
To test this feature, you will need to first upload a result, then delete that result from local storage (using any File Manager), then restart the app and check if the result is shown in the History screen (or see in the log console which results are downloaded).

**Review by freedomtan — APPROVED** [review]
LGTM

**Pull request merged**
