### PR TITLE
Adding docker for DLC generation

### PR DESCRIPTION
**Pull request by mohitmundhragithub**
The previous docker file was removed from the flutter version of the app. So, adding it back, to be used for DLC generation for QTI backend.

### CODE REVIEW

**Review by d-uzlov — DISMISSED** [review]

**Review by anhappdev — CHANGES_REQUESTED** [review]
Can you move the file `flutter/android/docker/dataset_models/Dockerfile` to `datasets/Dockerfile`? I think it's better organized that way.

**Comment by d-uzlov** [comment]
> Can you move the file `flutter/android/docker/dataset_models/Dockerfile` to `datasets/Dockerfile`?

I think it should be `datasets/docker/Dockerfile`, for consistency with other dockerfiles.

**Comment by mohitmundhragithub** [comment]
> > Can you move the file `flutter/android/docker/dataset_models/Dockerfile` to `datasets/Dockerfile`?
> 
> I think it should be `datasets/docker/Dockerfile`, for consistency with other dockerfiles.

the dockerfile is required to be used for model generation as well. So, thought of keeping it in flutter/android.

**Comment by mohitmundhragithub** [comment]
updated the paths

**Comment by anhappdev** [comment]
> the dockerfile is required to be used for model generation as well. So, thought of keeping it in flutter/android.

I did not test it, but would be great if we can use the already existed `flutter/android/docker/Dockerfile` instead of the newly uploaded `datasets/docker/Dockerfile`.

**Review by anhappdev — APPROVED** [review]

**Pull request merged**
