### PR TITLE
fix: add missing permission to access media on Android 13

### PR DESCRIPTION
**Pull request by anhappdev**
Per https://github.com/mlcommons/mobile_app_open/pull/562#issuecomment-1340480507
More info here:
https://developer.android.com/training/data-storage/shared/media#storage-permission

APK for testing:
[2022-12-08_mlperfbench-8d543c7-qsmgt.apk](https://drive.google.com/file/d/1hFQpng-Y-xvHO9PFcYwyJPyp90CVt0GP/view?usp=sharing)

### CODE REVIEW

**Comment by freedomtan** [comment]
LGTM, @AhmedTElthakeb and @mohitmundhragithub please help confirm that adding the permission resolve the issue @AhmedTElthakeb raised.

**Comment by freedomtan** [comment]
With the apk, I could not finish running Image Classification on either MTK devices or Google Pixel 6. I saw messages like

```
...
12-12 15:15:23.420  2208  2474 W System.err: java.lang.NumberFormatException: For input string: "????"
12-12 15:15:23.421  2208  2474 W System.err: 	at java.lang.Integer.parseInt(Integer.java:747)
12-12 15:15:23.421  2208  2474 W System.err: 	at java.lang.Integer.parseInt(Integer.java:865)
12-12 15:15:23.421  2208  2474 W System.err: 	at android.media.ExifInterface$ExifAttribute.getIntValue(ExifInterface.java:1006)
12-12 15:15:23.421  2208  2474 W System.err: 	at android.media.ExifInterface.handleThumbnailFromJfif(ExifInterface.java:4325)
12-12 15:15:23.421  2208  2474 W System.err: 	at android.media.ExifInterface.setThumbnailData(ExifInterface.java:4298)
12-12 15:15:23.421  2208  2474 W System.err: 	at android.media.ExifInterface.loadAttributes(ExifInterface.java:2030)
12-12 15:15:23.421  2208  2474 W System.err: 	at android.media.ExifInterface.<init>(ExifInterface.java:1565)
12-12 15:15:23.421  2208  2474 W System.err: 	at com.android.providers.media.MediaProvider.getRedactionRanges(MediaProvider.java:8807)
12-12 15:15:23.421  2208  2474 W System.err: 	at com.android.providers.media.MediaProvider.getRedactionRanges(MediaProvider.java:8780)
12-12 15:15:23.421  2208  2474 W System.err: 	at com.android.providers.media.MediaProvider.getRedactionRangesForFuse(MediaProvider.java:8762)
12-12 15:15:23.421  2208  2474 W System.err: 	at com.android.providers.media.MediaProvider.onFileOpenForFuse(MediaProvider.java:9017)
...
```

Apparently, there is some kind of number format issue. Running classification with CLI works fine.
```bash
adb  shell /data/local/tmp/mlprtf main external imagenet \
  --mode=AccuracyOnly --output_dir=/data/local/tmp/sr_output \
  --model_file=/data/local/tmp/v0_7/tflite/mobilenet_edgetpu_224_1.0_uint8.tflite  \
  --images_directory=/sdcard/test_data/mlperf_datasets/imagenet/img --offset=1 \
  --groundtruth_file=/sdcard/test_data/mlperf_datasets/imagenet/imagenet_val_full.txt  \
  --lib_path=/data/local/tmp/sr/libtflitebackend.so
```

We probably has this issue for a while.

**Comment by anhappdev** [comment]
> With the apk, I could not finish running Image Classification on either MTK devices or Google Pixel 6.

Does it work normally on devices with Android 12? Or does the error occur only on devices with Android 13?

**Comment by freedomtan** [comment]
> > With the apk, I could not finish running Image Classification on either MTK devices or Google Pixel 6.
> 
> Does it work normally on devices with Android 12? Or does the error occur only on devices with Android 13?

Didn't try on Android 12. With Android 13, it works fine when the default folder is used.

**Comment by freedomtan** [comment]
my guess is that a system service attempted to read ExIF information for directories other than `/sdcard/Android/data` and failed. The JPEG files in mlperf_datasets don't have ExIF information, so it failed....

**Comment by anhappdev** [comment]
I observed some strange behaviors on Android 12. The app can read image files `.jpg` but not other file types like `.pbtxt` or `.tfrecord` when using a custom folder. 

Per [Access documents and other files from shared storage](https://developer.android.com/training/data-storage/shared/documents-files)
> Because the user is involved in selecting the files or directories that your app can access, this mechanism doesn't require any [system permissions](https://developer.android.com/guide/topics/permissions/overview)

so I am not sure yet why the app cannot access those files.

**Comment by freedomtan** [comment]
> I observed some strange behaviors on Android 12. The app can read image files `.jpg` but not other file types like `.pbtxt` or `.tfrecord` when using a custom folder.
> 
> Per [Access documents and other files from shared storage](https://developer.android.com/training/data-storage/shared/documents-files)
> 
> > Because the user is involved in selecting the files or directories that your app can access, this mechanism doesn't require any [system permissions](https://developer.android.com/guide/topics/permissions/overview)
> 
> so I am not sure yet why the app cannot access those files.

same on Android 13, when I ran Object Detection only, I got 
```
...
12-13 09:13:39.761  3911 28743 I native  : cpp/flutter/dart_run_benchmark.cc:37 dataset_groundtruth_path=/storage/emulated/0/test_data/mlperf_datasets/coco/coco_val_full.pbtxt;
12-13 09:16:12.475  3245 31532 E MediaProvider: Permission to access file: /storage/emulated/0/test_data/mlperf_datasets/coco/coco_val_full.pbtxt is denied
...
```

**Comment by mohitmundhragithub** [comment]
i couldn't get hold of an android 13 device... 
but, on android 12 internal reference device, on selecting "downloads" as the custom folder... the app seem to be able to run all the cases.

**Comment by AhmedTElthakeb** [comment]
> I observed some strange behaviors on Android 12. The app can read image files `.jpg` but not other file types like `.pbtxt` or `.tfrecord` when using a custom folder.
> 

This is exactly what I have been observing.

**Comment by freedomtan** [comment]
@anhappdev will help checking against settings in our previous Android app. We probably had this issue back from Android 11, which means [android.permission.MANAGE_EXTERNAL_STORAGE](https://developer.android.com/training/data-storage/manage-all-files) and related settings may be the cause of the problem.

**Comment by anhappdev** [comment]
Adding the [android.permission.MANAGE_EXTERNAL_STORAGE](https://developer.android.com/training/data-storage/manage-all-files) and allow the app to access all files did resolve the issue with denied permission.

But I am looking for a way to resolve it without using that dangerous permission (which will also prevent the app to be published to the Play Store)

**Comment by anhappdev** [comment]
The old Android native app can access `/sdcard/mlperf_datasets` because it targeted Android 10 (API level 29)

https://github.com/mlcommons/mobile_app_open/blob/a47423a778debeb7d4dffcc4a9c69b2697171b93/android/java/org/mlperf/inference/AndroidManifest.xml#L9
and [opted out the scoped storage](https://developer.android.com/training/data-storage/use-cases#opt-out-in-production-app)
https://github.com/mlcommons/mobile_app_open/blob/a47423a778debeb7d4dffcc4a9c69b2697171b93/android/java/org/mlperf/inference/AndroidManifest.xml#L26

But it does not work with Android 11 (API level 30) anymore. Our Flutter app target API level 33, BTW.

**Comment by anhappdev** [comment]
I could not find out why it did not work. Maybe for now we can just add the `MANAGE_EXTERNAL_STORAGE` permission. And when we plan to publish the app on the Play Store, we will revive this one again.

Here is the new APK with the `MANAGE_EXTERNAL_STORAGE` permission:
[2022-12-19_mlperfbench-4043e38-qsmgt.apk](https://drive.google.com/file/d/1vKyRHLdZbBAQ39qT62LgrukRftPayUp0/view?usp=sharing)
Noted: I need to go to Device Settings -> Apps > MLPef Mobile > Permissions and manually allow management of all files.

**Comment by freedomtan** [comment]
> I could not find out why it did not work. Maybe for now we can just add the `MANAGE_EXTERNAL_STORAGE` permission. And when we plan to publish the app on the Play Store, we will revive this one again.
> 
> Here is the new APK with the `MANAGE_EXTERNAL_STORAGE` permission: [2022-12-19_mlperfbench-4043e38-qsmgt.apk](https://drive.google.com/file/d/1vKyRHLdZbBAQ39qT62LgrukRftPayUp0/view?usp=sharing) Noted: I need to go to Device Settings -> Apps > MLPef Mobile > Permissions and manually allow management of all files.

Maybe, in addition to manifest setting line, some extra code is needed for this permission?

**Review by freedomtan — APPROVED** [review]
confirmed that with this permission, I can run the app (with submission model on and my own data directory) on devices running Android 13.

**Comment by anhappdev** [comment]
> Maybe, in addition to manifest setting line, some extra code is needed for this permission?

The `ACTION_OPEN_DOCUMENT_TREE` intent action need to be used (per [Grant access to a directory's contents](https://developer.android.com/training/data-storage/shared/documents-files#grant-access-directory)). But the plugin already does that in [FilePickerDelegate.java#L231](https://github.com/miguelpruivo/flutter_file_picker/blob/0997d025a1d402f6844de026a4616305e0584be3/android/src/main/java/com/mr/flutter/plugin/filepicker/FilePickerDelegate.java#L231).

**Comment by freedomtan** [comment]
@mohitmundhragithub and @AhmedTElthakeb to test it this week.

**Comment by freedomtan** [comment]
Let's merge this and try to test on commercial Q devices and enhance permission asking callbacks (so that we don't need to add setting manually).

**Pull request merged**
